### PR TITLE
xtask ls-apis: try SSH access for dendrite

### LINKED ISSUE #6839: `omicron-ls-apis::test_dependencies` requires GitHub credentials or git rewrite rules
@andrewjstone reported the following issue with the new test added in #6831 which I can trivially reproduce:

```
$ cargo nextest run -p omicron-ls-apis
info: experimental features enabled: setup-scripts
    Finished `test` profile [unoptimized + debuginfo] target(s) in 1.03s
------------
 Nextest run ID 4e62629e-50cf-41fd-98eb-f159421dac1b with nextest profile: default
    Starting 1 test across 3 binaries
     Running [ 00:00:03] [                                                                                            ] 0/1: 1 running, 0 passed, 0 skipped
        FAIL [   4.367s] omicron-ls-apis::test_dependencies test_api_dependencies

--- STDOUT:              omicron-ls-apis::test_dependencies test_api_dependencies ---

running 1 test
test test_api_dependencies ... FAILED

failures:

failures:
    test_api_dependencies

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 4.34s


--- STDERR:              omicron-ls-apis::test_dependencies test_api_dependencies ---
thread 'test_api_dependencies' panicked at dev-tools/ls-apis/tests/test_dependencies.rs:25:5:
assertion `left == right` failed: stderr:
loading metadata for workspace omicron from current workspace
loading metadata for workspace crucible from /home/iliana/.cargo/git/checkouts/crucible-f3b5bdecdc6486d6/2b88ab8/Cargo.toml
loading metadata for workspace maghemite from /home/iliana/.cargo/git/checkouts/maghemite-de41bdd6c14939ab/056283e/Cargo.toml
loading metadata for workspace propolis from /home/iliana/.cargo/git/checkouts/propolis-12517f89d3d9f483/11371b0/Cargo.toml
Error: loading metadata

Caused by:
    `cargo metadata` exited with an error:     Blocking waiting for file lock on package cache
        Updating git repository `https://github.com/oxidecomputer/dendrite`
    error: failed to get `common` as a dependency of package `ddm v0.1.0 (/home/iliana/.cargo/git/checkouts/maghemite-de41bdd6c14939ab/056283e/ddm)`

    Caused by:
      failed to load source for dependency `common`

    Caused by:
      Unable to update https://github.com/oxidecomputer/dendrite?branch=main#4cdc7d7e

    Caused by:
      failed to fetch into: /home/iliana/.cargo/git/db/dendrite-627b239a911c6241

    Caused by:
      failed to authenticate when downloading repository

      * attempted to find username/password via git's `credential.helper` support, but failed

      if the git CLI succeeds then `net.git-fetch-with-cli` may help here
      https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

    Caused by:
      failed to acquire username/password from local configuration


  left: 1
 right: 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

   Canceling due to test failure
------------
     Summary [   4.369s] 1 test run: 0 passed, 1 failed, 0 skipped
        FAIL [   4.367s] omicron-ls-apis::test_dependencies test_api_dependencies
error: test run failed
```

This test works okay if you have your system configured in a particular way (either a GitHub token configured or a way to rewrite the HTTPS URL to an SSH one). This is a new requirement to run tests locally that I'd like to avoid having.

### PR DESCRIPTION
**Pull request by iliana**
Fixes #6839, at least from my perspective.

1. If running `cargo metadata` on the Maghemite workspace manifest fails, try re-running it with a set of environment variables that replaces Dendrite's Git URL with an SSH one. This removes the requirement to have a functioning ~/.netrc in order to run the full test suite locally; having a functioning SSH agent is significantly less hassle than fiddling with GitHub tokens.
2. Move the `cargo xtask ls-apis` exercising out of the already-quite-long build-and-test jobs. We've seen [a flake on main](https://buildomat.eng.oxide.computer/wg/0/details/01J9YK8K5ASNHCKRDKBKD97KFT/DbLBuHhEEklJzGRMi7NxyxdZmoqz8wsZNyoMVGTIZVnvCvch/01J9YK99F56A9R34C76TTFCE0Y#S4415) where it took just over an hour to get to the `ls-apis` bits by which time the GitHub token had already expired. build-and-test is already the longest required step to merge and it's not ideal to add more things to it.

### CODE REVIEW

**Comment by iliana** [comment]
Well that didn't work in CI as I had hoped.

**Comment by davepacheco** [comment]
The two logical changes here address different problems.  So commenting on those separately:

On the first one (re-trying a failed clone with different Git env vars to see if an ssh clone will work): I don't love the implicitness of this behavior.  I burned a lot of time debugging the https/ssh URL stuff the first time I ran into it and this feels like it layers on another level of complexity if it goes wrong.  This also doesn't feel like a really scalable solution, in that: the root problem here I think is only trying to use a private repo smoothly in both CI and locally, but this only fixes one particular dependency in one context.  (I realize this tool is a little weird for doing some of the cargo updating at runtime rather than before the build, but I don't think that fundamentally changes what's going on here?)  Would it not make sense for us to pick one standard way to do that and then use that everywhere?  Maybe that's changing the Maghemite dependency to use ssh URLs and use the https re-writing that we do in Omicron to make it work in CI?  Put differently: is there any reason _not_ to do that instead, aside from it being more work?  (That might well be a good reason -- just trying to understand the tradeoff.)

---

I'm not sure the second part of this (moving the `cargo xtask ls-apis` invocations) will fix the reported flake.  Since `ls-apis` opts into the hakari machinery, I expect that building it already depends on quite a lot of the Omicron build.  So I'm not sure moving it from "right after the build step in the `build-and-test` job" to "its own separate job [that builds most of Omicron]" is going to move the needle in terms of getting it done within the first hour.  Do we have any way to know?

In the reported flake, the failure was immediately preceded by a 40-*minute* `rustc` invocation.  That seems awfully long.  Is that common?

Some other ideas:

- We could extend the buildomat token mechanism to support jobs that take longer than an hour.  I think @jclulow had ideas for this.  This feels like it solves the more general problem, but I don't have a sense of how much work it is.
- Do these invocations in a separate buildomat job that uses binaries built by the build-and-test job.  This way, we're not using up any of the 60m building anything.
- If we want quick-and-dirty, I wonder if it would fix things to inject some `cargo metadata` invocations by hand before even building so Cargo is forced to download the Git deps and their deps so that it's already present by the time we get to them later.

**Comment by davepacheco** [comment]
We talked about this offline, with details summarized here: https://github.com/oxidecomputer/omicron/issues/6839#issuecomment-2415333106

The biggest shift for me is realizing that Dendrite is the exception (because it's private) rather than the rule, and the choice here isn't forever.  Given that, I think it makes less sense to invest in first-classing support for private repos.

**Comment by iliana** [comment]
Per the call yesterday we talked about moving the `xtask ls-apis` bit earlier. In good(?) news, the build timings are still probably accurate:

```
+ ptime -m cargo build -Z unstable-options --timings=json --workspace --tests --locked --verbose
       Dirty proc-macro2 v1.0.87: the rustflags changed
   Compiling proc-macro2 v1.0.87
       Dirty unicode-ident v1.0.13: the rustflags changed
   Compiling unicode-ident v1.0.13
       Dirty libc v0.2.159: the rustflags changed
   Compiling libc v0.2.159
```

> In the reported flake, the failure was immediately preceded by a 40-minute rustc invocation. That seems awfully long. Is that common?

That's certainly on the high end of the bell curve but I think within a few standard deviations of the mean.

**Pull request merged**
