### PR TITLE
[internal-dns] First pass at integrating service discovery codebase

### PR DESCRIPTION
**Pull request by smklein**
Ports https://github.com/davepacheco/toy-dns into Omicron as `internal-dns`:

- https://github.com/davepacheco/toy-dns/blob/main/src/client.rs -> `internal-dns-client`, so clients can depend on the bindings without depending on the server
- https://github.com/davepacheco/toy-dns/tree/main/src -> `internal-dns`, which holds the server library, binary, and API generator. The "toyadm" interface has, for the moment, been removed.
- https://github.com/davepacheco/toy-dns/tree/main/tests -> `internal-dns/tests`. Also adds a test for the generated OpenAPI file, and makes some minor tweaks via `serde(rename)` to ensure it passes our linter.

### CODE REVIEW

**Comment by davepacheco** [comment]
Thanks for doing this!  CC @rcgoodfellow.

I think it's worth keeping the CLI tool.  Maybe make it a binary in internal-dns-client?

**Comment by smklein** [comment]
> I think it's worth keeping the CLI tool. Maybe make it a binary in internal-dns-client?

Done, added as `dnsadm`

**Review by davepacheco — APPROVED** [review]
I haven't really reviewed most of the code here.  But at this point I think the risk is low and urgency is important -- we should land this so we can make forward progress on the things that need it.

**Comment by rcgoodfellow** [comment]
The prototype also as a testing workflow that runs the automated tests if you want to pick that up.

- https://github.com/davepacheco/toy-dns/blob/main/.github/workflows/rust.yml

**Review by rcgoodfellow — APPROVED** [review]
LGTM!

**Pull request merged**
