### PR TITLE
Update crucible and propolis

### PR DESCRIPTION
**Pull request by jmpesp**
Bump crucible rev to pick up:

- Do not eat ErrorReport messages related to repairs
- A bounced agent must reinitialize all SMF config
- Turn off show_work on every ds ping response
- Wait for ZFS snapshot directory + agent fixes
- Bump openssl from 0.10.48 to 0.10.55
- Bump h2 from 0.3.12 to 0.3.20
- Update Rust crate async-trait to 0.1.72
- Update Rust crate indicatif to 0.17.5
- Update Rust crate vergen to 8.2
- Update Rust crate omicron-zone-package to 0.9.1
- Update Rust crate rustls-pemfile to 1.0.3
- Update Rust crate signal-hook to 0.3.17
- Update Rust crate test-strategy to 0.3.1
- Update Rust crate itertools to 0.11.0
- Update Rust crate num-derive to 0.4
- Update Rust crate tokio to 1.29

Bump propolis rev to pick up:

- Bump crucible rev to latest
- Add xtask for checking license headers
- Make license headers consistent
- Tweak docs CI job and fix existing nits
- Disable PHD test in buildomat until CI is fixed
- propolis-server should use reservoir on prod gear
- PHD: add Ubuntu 22.04 guest adapter

Also ran `cargo update -p 'async-trait@0.1.71'`, then manually edited Cargo.lock to set ringbuffer's version to 0.14.1, because of a breaking change in 0.14.2.

### CODE REVIEW

**Comment by rcgoodfellow** [comment]
Just took a quick look at the deploy task failure. Looks like you may have hit something that I was hitting in local development. CRDB is failing to come up with errors like [this](https://buildomat.eng.oxide.computer/wg/0/artefact/01H6GZKPBT4465S8WQBYE7FCNC/YhYugUn23yMH72NJRcRHRakqUVwEii0b8aw1lXrwQhKe2Eu9/01H6GZKZ9KNAKC9MGKZRKK721F/01H6H3DEJHRJQQNNSF377WVQ88/oxide-sled-agent:default.log?format=x-bunyan#L528).

```
Failed to initialize CockroachDb: Error running command in zone 'oxz_cockroachdb_00d67179-4c76-470c-9108-bfad376719d9': Command [/opt/oxide/cockroachdb/bin/cockroach init --insecure --host [fd00:1122:3344:101::4]:32221] executed and failed with status: exit status: 1  stdout:   stderr: ERROR: cluster has already been initialized\nFailed running "init"\n
```

This seems to be somewhat random when it happens. I did include a fix for it in #3576 with [this change](https://github.com/oxidecomputer/omicron/commit/9bf3481cac8e349f692a845885d270bc4063dc54#diff-b8a6f13742cae29f44d095f6b9e8c2febc712e0ff86f01f3c8ec9d4e5d2db396R2709-R2722). This PR does not have that commit as it just landed on the main branch last night.

**Comment by jmpesp** [comment]
Thanks for having a look - I merged main into this, will check on CI later.

**Comment by jmpesp** [comment]
It's still failing, and I see 
```
SledAgent (InstanceManager): result of instance_ensure call is Err(Error Response: status: 500 Internal Server Error; headers: {"content-type": "application/json", "x-request-id": "0e7278fd-f4f1-492e-a52a-6083bcd4b7a9", "content-length": "124", "date": "Sun, 30 Jul 2023 02:24:09 GMT"}; value: Error { error_code: Some("Internal"), message: "Internal Server Error", request_id: "0e7278fd-f4f1-492e-a52a-6083bcd4b7a9" })
    file = sled-agent/src/instance.rs:456
    instance_id = dd3acc1e-44d4-42ed-8d22-3b7022f74081
```
from the job log [here](https://buildomat.eng.oxide.computer/wg/0/artefact/01H6J65QGC8EZN74AW3SK0HBG6/48MrhIR05ibLA4OtjvsQRhhJxvW7ulr562TIUw2T3wMNGWPo/01H6J662QQ28SSY8K57ZC9DNW7/01H6J9Q2HZ6WRDXQZ2X09N4NXY/oxide-sled-agent:default.log?format=x-bunyan#L572)

**Comment by jmpesp** [comment]
As I understand it, Propolis as of 7729616cd7403fad9cf3b07510bf852fc55135f4 requires that `vmm_reservoir_percentage` be set in a sled's config file to something non-zero. 44d539f conservatively sets this to 50%, where prod gear selects 80%.

**Review by rcgoodfellow — APPROVED** [review]

**Pull request merged**
