### PR TITLE
Add a traceable Diesel connection structure

### PR DESCRIPTION
**Pull request by smklein**
FYI @bnaecker - this might be an alternative to the issues we had in https://github.com/oxidecomputer/async-bb8-diesel/pull/7. 

I believe all the "Span" fundamentals mentioned in that PR are still relevant, but this attempts to expose the "raw DB interface to Diesel" a little more explicitly.

### CODE REVIEW

**Comment by bnaecker** [comment]
@smklein I'm finally circling back to this. I started to implement this in a standalone crate that we can push on crates.io, but it seems we're actually using a bleeding-edge version of diesel in omicron. I assume that's intentional and required, but it might mean it'd be easier or more appropriate to keep the traced connection in this repo. WDYT?

**Comment by smklein** [comment]
> @smklein I'm finally circling back to this. I started to implement this in a standalone crate that we can push on crates.io, but it seems we're actually using a bleeding-edge version of diesel in omicron. I assume that's intentional and required, but it might mean it'd be easier or more appropriate to keep the traced connection in this repo. WDYT?

Yeah, we use Diesel 2, which hasn't been released, so I depend on the github version. This prevents publishing to crates.io, but doesn't necessarily mean we can't split it out. [As an example](https://github.com/oxidecomputer/async-bb8-diesel/blob/22c26ef840075a57b18ac2eae3ead989b992773e/Cargo.toml#L14), async-bb8-diesel depends on the unreleased version of Diesel, but exists as a separate crate (just unpublished).

Either way is fine with me though. Easy to split out later if that's preferable.

**Comment by bnaecker** [comment]
@smklein Sounds good, I'll make it a separate crate on GH, a la `async-bb8-diesel`.

**Comment by bnaecker** [comment]
I'm closing this as we've now merged #488 based off this.

**Pull request closed without merging**
