### PR TITLE
add API for listing silo users

### LINKED ISSUE #1235: Endpoint to list silo users
The existing [`/users`](https://github.com/oxidecomputer/omicron/blob/846dbfd7867619a1c2a29a5527040d4595946890/nexus/src/external_api/http_entrypoints.rs#L3111-L3117) endpoint lists built-in system users. I've been using it to test my work on role assignment in the console, but I will need IdP users for it to really work.

Because we know the silo from the authenticated user, I don't think we need the silo in the path. That makes me wonder if we should use `/users` for silo users and rename the system users endpoint (`/system_users` etc).

### PR DESCRIPTION
**Pull request by davepacheco**
Fixes #1235.

This change:

* renames the existing /users (which lists built-in users) to /users_builtin.
* creates a new /users that lists Silo Users.  These objects only have a uuid in them right now.  They could eventually have external_id but I think that will depend on #1210.  Presumably we eventually want them to have display names too, but that too depends on figuring out if/how we get this as part of the SAML login.  (Since other systems do JIT with SAML and presumably also want to include display names, I'm guessing some SAML IdPs provide this using a mechanism similar to what they do for groups, but I don't really know.)

CC @david-crespo I'm not sure if this change will wind up breaking the console flow you have because there's only an "id" now.

### CODE REVIEW

**Comment by davepacheco** [comment]
This is ready for review but I'm leaving this as a draft because it depends on #1265.

**Comment by davepacheco** [comment]
There's one issue I need to fix: currently, only privileged users can list Silo users.  I imagine we'll want to make all users able to list users.

**Comment by david-crespo** [comment]
> There's one issue I need to fix: currently, only privileged users can list Silo users. I imagine we'll want to make all users able to list users.

Not sure. Any authenticated user? Feels wrong, but I can't think of a good reason why. Are you thinking because anyone can create a project, and therefore be an admin on that project, and then they have to list user to assign roles? _Can_ anyone create a project?

**Comment by david-crespo** [comment]
> Without this, you couldn't even see who else has access to the same thing that you have access to.

Yeah, that makes sense. Wasn't sure whether this is expected. In the GitHub web UI I can't see this on a private repo for which I'm not an admin because they block access to the whole settings view. But it turns out you can still get the list of collaborators from the API:

```
gh api /repos/oxidecomputer/<repo>/collaborators | jq '.[] | { login, permissions }'
```

I wonder if there's a distinction to be made between listing users on a particular resource and enumerating all users?

**Comment by davepacheco** [comment]
> I wonder if there's a distinction to be made between listing users on a particular resource and enumerating all users?

It's possible but tricky.  I imagine we'll eventually add a `/users/$uuid` endpoint for looking up a specific user.  It's not really feasible for that to check whether you and the requested user share any resources in common.  We could provide that information when you list the policy (and not if you request the same user explicitly).  It'd be a little inconsistent but maybe pragmatic.

It seems surprising to me that people would want to put two people in the same Silo that couldn't know about each other.  Wouldn't you use different Silos for that?  But if we're not sure, we can raise this with product.

**Comment by davepacheco** [comment]
Okay, this version lets all users see all users in their own Silo.  I added this endpoint to the allowlist of things without authz test coverage because the test doesn't currently support endpoints that are totally public for all authenticated users.  I will file a new ticket for this though because we have a couple of them now.

**Review by david-crespo — APPROVED** [review]
Very straightforward.

**Pull request merged**
