### PR TITLE
Update crucible

### PR DESCRIPTION
**Pull request by smklein**
I *think* this is blocking https://github.com/oxidecomputer/omicron/pull/1902 , because it's causing that PR to fail with a similar failure mode.

### CODE REVIEW

**Review by leftwo — COMMENTED** [review]
Do we also need propolis to be updated as well?

**Comment by leftwo** [comment]
> Do we? Has there been an API-breaking change in the past few months?

There have been a few changes to the message protocol between upstairs and downstairs (and
one that is currently in review) so depending on where propolis is, it could be incompatible with
latest.  I'll go check and report back here.

**Comment by leftwo** [comment]
So, we do need propolis to move forward.
Propolis is at: 894d44988c56713105bbbd07900d628781ab4dda
```
commit 894d44988c56713105bbbd07900d628781ab4dda
Author: liffy <629075+lifning@users.noreply.github.com>
Date:   Wed Feb 8 11:18:54 2023 -0800
```

And, a change in message protocol happened here:
```
commit 75519cb2dc91be78ee5792718575e5348ddbdc1c
Author: Alan Hanson <alan@oxidecomputer.com>
Date:   Mon Feb 27 05:50:15 2023 -0800 
```

So, at a minimum propolis will need that.

**Review by leftwo — COMMENTED** [review]
When Gregs update to propolis lands, we will want that to be included here as well.

**Review by jmpesp — APPROVED** [review]

**Pull request merged**
