### PR TITLE
Instance to VmInstance

### PR DESCRIPTION
**Pull request by ryaeng**
Changing the ambiguous type of Instance to VmInstance at the web, app, and db layers.

See #1192 for the request.

### CODE REVIEW

**Comment by ryaeng** [comment]
@smklein @david-crespo Could either of you review my pull request?

**Comment by david-crespo** [comment]
Yes, but we're working toward an internal deadline and will likely not get to this until next week.

**Comment by ryaeng** [comment]
> Yes, but we're working toward an internal deadline and will likely not get to this until next week.

Lemme know if there's anything I can do to help.

**Comment by zephraph** [comment]
Given we're not actively pursuing this at the moment and there are a lot of in-flight changes I'm going to close this. We can always re-open and revisit if later if we decide to.

**Pull request closed without merging**
