### PR TITLE
Update Crucible and Propolis

### PR DESCRIPTION
**Pull request by bnaecker**

### CODE REVIEW

**Comment by pfmooney** [comment]
Does it make sense to wait for oxidecomputer/propolis#747 to land?

**Comment by bnaecker** [comment]
> Does it make sense to wait for [oxidecomputer/propolis#747](https://github.com/oxidecomputer/propolis/pull/747) to land?

Sure, we can bundle those here, that makes sense.

**Comment by bnaecker** [comment]
Looks like there's a failure to launch an instance in the deploy test, [here](https://buildomat.eng.oxide.computer/wg/0/details/01J6AKFJRKWJPS37CVJHG4DSS0/ART3IgYELS66I1BhAJN1DYEUcCNv3ju6WVfa08cYtqryQY4R/01J6AKG5T6KS0P7MPDJRB5F6VJ#S1183). It seems like that's real, and may be due to some changes in Propolis I wasn't aware of. Maybe @gjcolombo or @hawkw has more info on that failure?

**Comment by bnaecker** [comment]
Thanks @hawkw. It's possible Propolis panicked, though I've tested this several times now. I'll give a whirl locally and look at the logs.

**Comment by hawkw** [comment]
Aaaaand it looks like Propolis has, indeed, failed to start: https://buildomat.eng.oxide.computer/wg/0/artefact/01J6AKFJRKWJPS37CVJHG4DSS0/ART3IgYELS66I1BhAJN1DYEUcCNv3ju6WVfa08cYtqryQY4R/01J6AKG5T6KS0P7MPDJRB5F6VJ/01J6APH53H72QA69KDSA063TG0/oxide-sled-agent:default.log?format=x-bunyan#L2604, returning a 500 Internal Server Error with no useful message.

Unfortunately, it looks like there aren't any logs from the Propolis  process in the test run?

**Comment by bnaecker** [comment]
> Unfortunately, it looks like there aren't any logs from the Propolis process in the test run?

Yeah, I think the zone is gone by the time we collect them, or we only do so from live zones maybe. I'll keep digging.

**Comment by gjcolombo** [comment]
Ruh-roh:

`SledAgent (InstanceManager): vmm setup failed: Err(Propolis(Error Response: status: 500 Internal Server Error; headers: {"content-type": "application/json", "x-request-id": "d79ab988-e7c4-4413-9380-fb660ccb5ac0", "content-length": "124", "date": "Tue, 27 Aug 2024 19:55:15 GMT"}; value: Error { error_code: Some("Internal"), message: "Internal Server Error", request_id: "d79ab988-e7c4-4413-9380-fb660ccb5ac0" }))`

Unfortunately we don't seem to have gotten any Propolis logs or a bundle from this particular test run. I think this is because the "ensure request failed" path doesn't actually go through the regular `InstanceRunner::terminate` flow that would cause a bundle to be collected. I'll file an issue for this, but we'll still need to investigate what happened here, probably by running this branch in a dev environment and seeing if we can grab logs directly from it.

**Comment by hawkw** [comment]
> > Unfortunately, it looks like there aren't any logs from the Propolis process in the test run?
> 
> Yeah, I think the zone is gone by the time we collect them, or we only do so from live zones maybe. I'll keep digging.

Thanks, if you can manage to get logs from the Propolis, that would be great --- it's probably worth looping in @gjcolombo, because this *might* be related to some of his recent propolis-server API refactoring --- maybe we're parsing something weirdly?

**Comment by bnaecker** [comment]
Well, at least I can repro it locally. I'm patching things to generate a zone bundle in this case, so at least we'll have logs and cores.

**Comment by bnaecker** [comment]
I've got to run for a while, but here's the failure:

```
{"msg":"request completed","v":0,"name":"propolis-server","level":30,"time":"2024-08-27T22:06:02.849971242Z","hostname":"oxz_propolis-server_d28d2aaa-88f6-486c-a5ab-3adbf6859bc5","pid":10432,"uri":"/instance","method":"PUT","req_id":"7943ba37-34d8-40b5-892c-7e807d7be422","remote_addr":"[fd00:1122:3344:101::1]:38280","local_addr":"[fd00:1122:3344:101::1:9]:12400","error_message_external":"Internal Server Error","error_message_internal":"VM initialization failed: Backend test-3be20cee-0d96-4fc9-921e-66d-2857e7 not found for storage device test-3be20cee-0d96-4fc9-921e-66d-2857e7","latency_us":71803,"response_code":"500"}
```

This is supposed to be looking up the Crucible backend for the virtual block device, but apparently I've borked the logic for finding that backend. I'm not sure how yet, since this worked deploying block devs backed by Crucible locally.

**Comment by gjcolombo** [comment]
I think I broke this in oxidecomputer/propolis#743. Working on a fix.

**Comment by gjcolombo** [comment]
Filed https://github.com/oxidecomputer/propolis/issues/750 to track.

**Comment by gjcolombo** [comment]
@bnaecker: this should be fixed by https://github.com/oxidecomputer/propolis/pull/751--you'll just need to update the Propolis deps once that merges. Sorry for the trouble!

**Comment by bnaecker** [comment]
@gjcolombo All good, thanks for the quick fix! We're going to wait for the networking metrics to be integrated anyway, so not a huge rush. 

But I'm glad we found this. Was there any more testing I could have done locally in Propolis to suss this out?

**Comment by gjcolombo** [comment]
> Was there any more testing I could have done locally in Propolis to suss this out?

The automated test gap here is that we don't have anything in Propolis CI that exercises the "regular" instance ensure API that Omicron uses. PHD uses a different instance ensure endpoint that gives it finer-grained control over the VM components it creates. The bug here was in the shim that converts from the Omicron endpoint's arguments to the PHD endpoint's arguments (so a little earlier in the instance startup process than PHD is able to catch). You (or really I, since this was my bug) could have caught this in manual testing by starting a VM using `propolis-cli` and passing JSON files containing Crucible disk requests on the command line (via the `--crucible-disks` parameter when invoking `propolis-cli new`).

In the long run my hope (I won't call it an "expectation" yet) is that the existing `InstanceEnsureRequest` API will be deprecated and that sled agent will switch over to using the instance-spec based API that PHD uses. But that's a ways off.

**Comment by bnaecker** [comment]
@zeeshanlakhani Let me know when your instance NIC PR in Propolis merges, and I can update this PR with those commits. That'll also pull in @gjcolombo's fix for the backend-mapping issue.

**Comment by zeeshanlakhani** [comment]
> @zeeshanlakhani Let me know when your instance NIC PR in Propolis merges, and I can update this PR with those commits. That'll also pull in @gjcolombo's fix for the backend-mapping issue.

Yep. I'm finishing testing today.

**Comment by hawkw** [comment]
We've merged oxidecomputer/propolis#751, which should fix the Propolis issue. Updating to pick that up should fix the test.

**Comment by zeeshanlakhani** [comment]
Did rebase here as the deps changed over a ton. Now, with just the bits for crucible and propolis.

**Review by iliana — APPROVED** [review]

**Pull request merged**
