### PR TITLE
Update lookup fns introduced in the V1 API to return `lookup::*` over `authz::*`

### PR DESCRIPTION
**Pull request by zephraph**
This PR is mostly in response to @davepacheco's feedback on #1957. Special thanks to @smklein for helping work through some rust lifetime issues here. 

Previously the `instance_lookup` and `project_lookup` functions returned a `authz::Instance` or `authz::Project` respectively that was authorized with read permissions. The challenge here is that this meant that in several places we required duplicate lookups to be able to resolve the instance with the right permissions. To avoid that we're passing around the lookup step itself instead.

### CODE REVIEW

**Review by david-crespo — APPROVED** [review]
Awesome. It feels very clearly like the way it's meant to be done. We've been working our way here for [at least a year](https://github.com/oxidecomputer/omicron/issues/485)!

**Comment by augustuswm** [comment]
Overall this makes sense to me. I don't know enough about Nexus to know if this would work or fit with existing patterns, but following this pattern we are likely to end up with a lot of match cases for project scoped resources that mirror:

```rust
ResourceSelector {
    resource: NameOrId::Name(resource_name),
    project: Some(NameOrId::Name(project_name)),
    organization: Some(NameOrId::Id(organization_id)),
} => {
    // ...
}
ResourceSelector {
    resource: NameOrId::Name(resource_name),
    project: Some(NameOrId::Name(project_name)),
    organization: Some(NameOrId::Name(organization_name)),
} => {
    // ...
}
```

Outside the scope of this PR, but maybe `InstanceSelector` could look like:

```rust
struct InstanceSelector {
    pub instance: NameOrId,
    pub project: Option<ProjectSelector>,
}
```

which would reduce the needed branches per selector. Following this path though would unfortunately start replicating a lot of the logic already encoded in the the `db::lookup` enums.

This shouldn't block this PR, but from my limited reading, it seems like with Selectors we are starting to encode the hierarchy of resources in multiple places.

**Comment by augustuswm** [comment]
Right, I should have been clearer (and used a different name) on that. It would end up as a different struct, such that the chain became `Params -> Selector -> Lookup`

**Comment by zephraph** [comment]
I agree generally with the feedback here. I'm going to merge this PR and do a few more endpoints (definitely those lower in the tree like project and org). After those are all in, I'll start investigating scoping things down for composability.

**Comment by zephraph** [comment]
I agree generally with the feedback here. I'm going to merge this PR and do a few more endpoints (definitely those lower in the tree like project and org). After those are all in, I'll start investigating scoping things down for composability.

**Pull request merged**
