### PR TITLE
More carefuly opte publisher installation

### PR DESCRIPTION
**Pull request by bnaecker**
- Remove any publishers with the expected names before installing
- If we're updating the publisher archive, just update the existing
  publisher's origin
- Don't verify the entire order, just check that `helios-dev` is last

### CODE REVIEW

**Comment by bnaecker** [comment]
This tries to address another issue @smklein ran into installing OPTE, where we might have more than one publisher with the expected name (e.g., "helios-netdev"). This wipes any existing publisher with the names we care about, if there are more than 1. If there's exactly 1, we just update its origin to the new archive file. If there are zero, it's installed as usual.

I've tried this with a bunch of configurations now.

- Nothing at all
- Everything up to date
- One publisher up to date, and one out of date
- Publishers listed in the wrong order
- One publisher missing
- One publisher having multiple origins (e.g., multiple lines in the output of `pkg publisher`)

I think this operates correctly in all these situations, in that we end up at the desired state of exactly one origin archive file for each of `helios-netdev` and `on-nightly`, pointing to the `opte.p5p` and `repo.p5p` archive files respectively.

**Comment by plotnick** [comment]
Thank you for this. I also ran into this on installation, and fixed it manually by consulting `pkg(1)`; but automatically doing the right thing here is clearly preferable.

**Comment by bnaecker** [comment]
Thanks @plotnick, apologies this has been so frustrating for everyone.

**Comment by bnaecker** [comment]
So after conferring with Josh, I think I may update this more. These notes are mostly for myself, though others are welcome to read and / or suggest ideas.

The issue is mostly around the xde kernel bits, which are part of a publisher with the name `on-nightly`. That will change in the future, but until then there's a possible conflict with someone who builds illumos locally, since that usually creates a publisher named `on-nightly`. Additionally, any updates to that publisher's archive will require a new BE. So why not use a BE for everything anyway?

In particular, we could:

- Download the SHAs and check if there are existing publishers with archives whose SHAs match those
- If so, do nothing, otherwise.
- Create a new BE
- Use a pretty blunt set of packaging commands, to install the new repo(s) as publishers into that BE, e.g., with `pkg -R /path/to/be/root`. Those can be "blunt" because there is no chance we clobber existing publishers in an irreversible way in that BE.
- If anything fails, just don't use the BE and / or delete it
- If it succeeds, remind the user they'll need to reboot for the changes to take effect

**Comment by bnaecker** [comment]
Ok, I think the BE-based approach is a large-enough amount of work that I'd prefer to merge this as-is. It should help folks like @plotnick and @smklein from hitting similar snags, and I can do the BE version in a later PR.

**Pull request merged**
