### PR TITLE
update to Rust 1.78.0 / bump OPTE to 0.29.250

### PR DESCRIPTION
**Pull request by iliana**
The most severe changes in this PR are dead code removal; I am not exactly sure why, but it seems like dead code detection became a little more robust between 1.77 and 1.78.

The 1.78.0 toolchain includes two new Clippy lints that are fixed in this PR:

- [**assigning_clones**](https://rust-lang.github.io/rust-clippy/master/index.html#/assigning_clones) identifies cases where some value is set to the clone of another value where that type has a custom `Clone::clone_from` implementation. In this particular case we see this with `Vec<_>`, which [has a more efficient implementation](https://doc.rust-lang.org/1.78.0/src/alloc/vec/mod.rs.html#2778).
- [**unnecessary_get_then_check**](https://rust-lang.github.io/rust-clippy/master/index.html#/unnecessary_get_then_check) identifies uses of `.get().is_some()` / `.get().is_none()` on map types, suggesting `.contains()` / `.contains_key()` instead. (In [one case](https://github.com/oxidecomputer/omicron/compare/oxidecomputer:25bcfec...oxidecomputer:73d3c9f#diff-4ed52f39a3e48ed13ee90a6db0ec540ac77b4ddbcd5e10e0179e29c65dfdda86) this identified a HashSet contains-then-insert, which is unnecessary due to [how `HashSet::insert` works](https://doc.rust-lang.org/1.78.0/std/collections/hash_set/struct.HashSet.html#method.insert).)

### CODE REVIEW

**Comment by iliana** [comment]
[Interesting:](https://buildomat.eng.oxide.computer/wg/0/artefact/01HXDKSYDNP1YXFRVFP2ZRSNDA/9lEm5MXpBdPO8UQZHmGRfgQPkGAXQzPGRkrXYSTgqWvK4EJO/01HXDKT6YYQTE3PX5X88ZMPGW0/01HXDQ5G5VT3TT7Y73FP3DMBXD/oxide-sled-agent:default.log?format=x-bunyan#L15)

```
thread 'main' panicked at /home/build/.cargo/git/checkouts/opte-c3062ea19cee8fd4/7ee353a/lib/opte-ioctl/src/lib.rs:294:9:
assertion failed: rioctl.resp_len_actual != 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by iliana** [comment]
OPTE fix at https://github.com/oxidecomputer/opte/pull/527

**Review by jgallagher — APPROVED** [review]
Thanks - all the code changes LGTM. I'm a little nervous about the `helios/deploy` failure, but I don't see any smoking guns there - just NTP failing to sync, which I think is a known flake (#5598).

**Comment by iliana** [comment]
It has now happened twice in a row, which is kind of concerning (I hit retry once already).

**Comment by FelixMcFelix** [comment]
I had a quick peek [at the logs there](https://buildomat.eng.oxide.computer/wg/0/details/01HXXBNPS6HR3X7BT9X3P0Y8XE/41gsBIUaozbpdtMxYqrdhsWOkOJAwHYYh50Emy4FvWxL4iOU/01HXYFDYPAWA2XZ0BFP0YSNBA1#S2220):

```
2024-05-15T16:15:46.446Z	+ pfexec /opt/oxide/opte/bin/opteadm dump-v2b
2024-05-15T16:15:46.446Z	Virtual to Boundary Mappings
2024-05-15T16:15:46.446Z	======================================================================
2024-05-15T16:15:46.446Z	
2024-05-15T16:15:46.446Z	IPv4 mappings
2024-05-15T16:15:46.446Z	----------------------------------------------------------------------
2024-05-15T16:15:46.446Z	TUNNELED PREFIX  BOUNDARY IP  VNI
2024-05-15T16:15:46.446Z	
2024-05-15T16:15:46.446Z	IPv6 mappings
2024-05-15T16:15:46.447Z	----------------------------------------------------------------------
2024-05-15T16:15:46.447Z	TUNNELED PREFIX  BOUNDARY IP  VNI
2024-05-15T16:15:46.447Z
```

I don't think this is a flake. Part of an OPTE API bump now is that you need to update maghmemite and its binaries to a compatible version, as `mgd` also inserts V2B mapping using the `opte-ioctl` crate. Levon's RPW work does this [here](https://github.com/oxidecomputer/omicron/pull/5568/files#diff-04c6efe7776b937b12d3ca7c58d8500ca455359885e55979cde60b62395fe443), among other spots. The most obvious consequence is that if the API version changes, you lose external connectivity.

**Comment by iliana** [comment]
Aha. I will hold off on this until that can get merged then.

**Pull request merged**
