### PR TITLE
Fixes bug causing overlap of SNAT and Ephemeral IP address port ranges

### PR DESCRIPTION
**Pull request by bnaecker**

### CODE REVIEW

**Comment by bnaecker** [comment]
This is intended to resolve #1793.

In addition to the unit test I wrote for this, I also tested this in the wild. I spun up the control plane as usual, and created 5 guests. Each had both and SNAT and Ephemeral IP. Since we're chunking up the port range for SNAT addresses into quadrants, in the original implementation, we would see that guest's SNAT range overlap with the second guest's Ephemeral IP address. Here's what we see running from this branch:

```
bnaecker@feldspar : ~/opte $ pfexec ./opteadm/target/debug/opteadm dump-layer -p opte0 nat
Layer nat
======================================================================
Inbound Flows
----------------------------------------------------------------------
PROTO  SRC IP           SPORT  DST IP           DPORT  HITS     ACTION
UDP    8.8.8.8          53     192.168.1.211    33614  0        NAT

Outbound Flows
----------------------------------------------------------------------
PROTO  SRC IP           SPORT  DST IP           DPORT  HITS     ACTION
UDP    172.30.0.5       33614  8.8.8.8          53     0        NAT

Inbound Rules
----------------------------------------------------------------------
ID       PRI    PREDICATES                                       ACTION
0        10     inner.ip.dst=192.168.1.211                       "STATEFUL: 172.30.0.5 <=> 192.168.1.211"

Outbound Rules
----------------------------------------------------------------------
ID       PRI    PREDICATES                                       ACTION
0        10     inner.ether.ether_type=0x800 meta: router-target=ig  "STATEFUL: 172.30.0.5 <=> 192.168.1.211"
1        100    inner.ether.ether_type=0x800 meta: router-target=ig  "STATEFUL: 192.168.1.210:0-16383"

bnaecker@feldspar : ~/opte $ pfexec ./opteadm/target/debug/opteadm dump-layer -p opte4 nat
Layer nat
======================================================================
Inbound Flows
----------------------------------------------------------------------
PROTO  SRC IP           SPORT  DST IP           DPORT  HITS     ACTION
UDP    8.8.8.8          53     192.168.1.216    36003  0        NAT

Outbound Flows
----------------------------------------------------------------------
PROTO  SRC IP           SPORT  DST IP           DPORT  HITS     ACTION
UDP    172.30.0.9       36003  8.8.8.8          53     0        NAT

Inbound Rules
----------------------------------------------------------------------
ID       PRI    PREDICATES                                       ACTION
0        10     inner.ip.dst=192.168.1.216                       "STATEFUL: 172.30.0.9 <=> 192.168.1.216"

Outbound Rules
----------------------------------------------------------------------
ID       PRI    PREDICATES                                       ACTION
0        10     inner.ether.ether_type=0x800 meta: router-target=ig  "STATEFUL: 172.30.0.9 <=> 192.168.1.216"
1        100    inner.ether.ether_type=0x800 meta: router-target=ig  "STATEFUL: 192.168.1.215:0-16383"

bnaecker@feldspar : ~/opte $
```

The last line is the relevant one. On `main` that address and port range would read `192.168.1.211:16384-32767`. That's because the query only checked that a candidate SNAT record does not have the _same_ port as any existing external IP records. That means we can't take the _first_ port quadrant, but the query would not prevent us from taking the remaining quadrants. With this fix in place, we no longer steal from the Ephemeral IP.

**Comment by bnaecker** [comment]
@jclulow Looks like the failing `helios-deploy` job is due to a version mismatch between `xde` and the userland library. Would you be so kind as to push the button that rolls a new image, when you have a moment?

**Review by davepacheco — APPROVED** [review]

**Comment by jclulow** [comment]
> @jclulow Looks like the failing `helios-deploy` job is due to a version mismatch between `xde` and the userland library. Would you be so kind as to push the button that rolls a new image, when you have a moment?

Looking at the failure I'm a bit confused:

```
BadApiVersion { user: 14, kernel: 15 }
```

It seems like this software is older than the new opte bits?  Does that mean this change needs to be rebased forwards?

**Comment by bnaecker** [comment]
Indeed it does, I had a stale `main` from which I branched. Thanks @jclulow, should be OK now since `main` builds fine.

**Pull request merged**
