### PR TITLE
clickhouse: add v21.10.4.26 for Linux and illumos

### PR DESCRIPTION
**Pull request by jclulow**

### CODE REVIEW

**Comment by jclulow** [comment]
NB: I have no idea from whence the current v21.7 Mac OS X binary originates.  It doesn't seem like ClickHouse produce Mac OS X binaries for the release versions.

**Comment by jclulow** [comment]
Somebody with an appropriate Macintosh could probably grab the source archive:

https://github.com/ClickHouse/ClickHouse/releases/download/v21.10.4.26-stable/ClickHouse_sources_with_submodules.tar.gz

And then build it according to the instructions:

https://clickhouse.com/docs/en/development/build-osx/

And then we can stash it in the S3 bucket.

**Comment by bnaecker** [comment]
Thanks for doing this Josh! I built the macOS version on my laptop, using the [`garbage-compactor` PR](https://github.com/oxidecomputer/garbage-compactor/pull/1) I put up a while back. Did you base your builds off these patches? IIRC, there are no patches to the _source_ for macOS, only the configuration files that are baked into the executable.

I'm happy to build the macOS version, just let me know what code you actually used to do this so I can pass it through the same tubes.

**Comment by karencfv** [comment]
We're on 22.8.9.24 now, I think it's safe to close this PR?

**Comment by citrus-it** [comment]
> We're on 22.8.9.24 now, I think it's safe to close this PR?

Yes, and I'm working on upgrading to v23.8.7.24. Closing.

**Pull request closed without merging**
