### PR TITLE
prototype oxide-client as progenitor-derived

### PR DESCRIPTION
**Pull request by ahl**
@iliana would love to hear if you try this out; I found that `cargo doc -p oxide-client --open` was a good place to start

### CODE REVIEW

**Comment by iliana** [comment]
Some immediate feedback: splitting up the various methods into separate traits based on tags is nice for organizing the documentation, but having to import each individual trait is kind of a pain. I think it would be nice if I could `use oxide_client::prelude::*` to just get all the traits in scope, similar to preludes in other libraries (e.g. [rayon](https://docs.rs/rayon/latest/rayon/prelude/index.html)).

**Comment by ahl** [comment]
That's a cool idea. Do I just make a `pub mod` named "prelude" or is there some special sorcery?

Thanks for kicking the tires.

**Comment by ahl** [comment]
@karencfv FYI

**Comment by iliana** [comment]
> Do I just make a `pub mod` named "prelude" or is there some special sorcery?

Yep, exactly. And then some `pub use crate::...` in the prelude.rs.

**Comment by iliana** [comment]
I rebased this branch and have been using these commits to develop our first end-to-end test for CI, and it's going pretty well — my problems tend to be related to things that aren't this generated client. I think it's ready for a merge.

**Comment by ahl** [comment]
I think the changes to the API are no longer needed to satisfy progenitor; testing that now.

**Review by smklein — APPROVED** [review]
Ship it!

**Pull request merged**
