### PR TITLE
Add Rust Cache Action to Github Actions

### PR DESCRIPTION
**Pull request by smklein**
This PR integrates the [Rust Cache Action](https://github.com/marketplace/actions/rust-cache) to cache third party dependencies. It exclusively applies them to Github workflows, and does not yet optimize Buildomat. The cache step is skipped on `main` so it will always build from scratch there.

Before Cache:
image

After Cache:
image

### CODE REVIEW

**Comment by smklein** [comment]
Note: this does not yet add a cache for the buildomat action, but it at least makes the Github actions much faster when third-party dependencies are unchanged.

**Comment by david-crespo** [comment]
This means it worked, right? Holy crap.

image

**Review by david-crespo — APPROVED** [review]
incredible!

**Comment by smklein** [comment]
> This means it worked, right? Holy crap.
> 
> image

I believe this particular image is referencing the cache for Clickhouse/Cockroach being downloaded: https://github.com/oxidecomputer/omicron/blob/ab8872a9540ba6af727a1c806e12d9209a4ed7f9/.github/workflows/rust.yml#L97-L116

This is the part of the action where we check for a cache:

image

**Comment by david-crespo** [comment]
I meant the build taking 5 minutes!

**Comment by smklein** [comment]
> I meant the build taking 5 minutes!

oh yeah I hope so lol

**Comment by david-crespo** [comment]
As discussed in chat, is there a way to make the use of the cache conditional so we can skip it on main? We would also have to turn off whatever it is that skips builds on main when it thinks the PR already handled it.

**Comment by david-crespo** [comment]
Branch skipping works. Tested by telling it to skip this branch instead of `main`:

image

**Pull request merged**
