### PR TITLE
Break OxQL queries for huge key sets into chunks

### LINKED ISSUE #5405: Nexus returns a 500 when running large OxQL queries
@david-crespo was showing me the magic that is The Browser, where one can call any of the Nexus API methods easily from the browser console. I was excited, and ran this OxQL query:

```
get virtual_machine:vcpu_usage | filter timestamp > @now() - 30s | group_by [instance_id]
```

That yields a 500 from Nexus. Digging into the logs for the instance that served it, we see:

```
BRM44220011 # grep  5390d360 /pool/ext/e126ddcc-8bee-46ba-8199-2a74df0ba040/crypt/zone/oxz_nexus_65a11c18-7f59-41ac-b9e7-680627f996e7/root/var/svc/log/oxide-nexus\:default.log  | looker
21:07:40.515Z DEBG 65a11c18-7f59-41ac-b9e7-680627f996e7 (dropshot_external): roles
    actor_id = 971bfcf1-dd5f-4bd0-95fe-59e006b0b870
    authenticated = true
    local_addr = 172.30.2.5:443
    method = POST
    remote_addr = 172.20.17.106:54007
    req_id = 5390d360-c899-42c1-8004-d35275fd18d9
    roles = RoleSet { roles: {} }
    uri = https://oxide.sys.rack2.eng.oxide.computer/v1/timeseries/query
21:07:40.515Z DEBG 65a11c18-7f59-41ac-b9e7-680627f996e7 (dropshot_external): authorize result
    action = Query
    actor = Some(Actor::SiloUser { silo_user_id: 971bfcf1-dd5f-4bd0-95fe-59e006b0b870, silo_id: 7bd7623a-68ed-4636-8ecb-b59e3b068787, .. })
    actor_id = 971bfcf1-dd5f-4bd0-95fe-59e006b0b870
    authenticated = true
    local_addr = 172.30.2.5:443
    method = POST
    remote_addr = 172.20.17.106:54007
    req_id = 5390d360-c899-42c1-8004-d35275fd18d9
    resource = Database
    result = Ok(())
    uri = https://oxide.sys.rack2.eng.oxide.computer/v1/timeseries/query
21:07:40.517Z DEBG 65a11c18-7f59-41ac-b9e7-680627f996e7 (dropshot_external): roles
    actor_id = 971bfcf1-dd5f-4bd0-95fe-59e006b0b870
    authenticated = true
    local_addr = 172.30.2.5:443
    method = POST
    remote_addr = 172.20.17.106:54007
    req_id = 5390d360-c899-42c1-8004-d35275fd18d9
    roles = RoleSet { roles: {} }
    uri = https://oxide.sys.rack2.eng.oxide.computer/v1/timeseries/query
21:07:40.517Z DEBG 65a11c18-7f59-41ac-b9e7-680627f996e7 (dropshot_external): authorize result
    action = Query
    actor = Some(Actor::SiloUser { silo_user_id: 971bfcf1-dd5f-4bd0-95fe-59e006b0b870, silo_id: 7bd7623a-68ed-4636-8ecb-b59e3b068787, .. })
    actor_id = 971bfcf1-dd5f-4bd0-95fe-59e006b0b870
    authenticated = true
    local_addr = 172.30.2.5:443
    method = POST
    remote_addr = 172.20.17.106:54007
    req_id = 5390d360-c899-42c1-8004-d35275fd18d9
    resource = Database
    result = Ok(())
    uri = https://oxide.sys.rack2.eng.oxide.computer/v1/timeseries/query
21:07:40.520Z DEBG 65a11c18-7f59-41ac-b9e7-680627f996e7 (dropshot_external): roles
    actor_id = 971bfcf1-dd5f-4bd0-95fe-59e006b0b870
    authenticated = true
    local_addr = 172.30.2.5:443
    method = POST
    remote_addr = 172.20.17.106:54007
    req_id = 5390d360-c899-42c1-8004-d35275fd18d9
    roles = RoleSet { roles: {(Silo, 7bd7623a-68ed-4636-8ecb-b59e3b068787, "admin")} }
    uri = https://oxide.sys.rack2.eng.oxide.computer/v1/timeseries/query
21:07:40.522Z DEBG 65a11c18-7f59-41ac-b9e7-680627f996e7 (dropshot_external): authorize result
    action = Read
    actor = Some(Actor::SiloUser { silo_user_id: 971bfcf1-dd5f-4bd0-95fe-59e006b0b870, silo_id: 7bd7623a-68ed-4636-8ecb-b59e3b068787, .. })
    actor_id = 971bfcf1-dd5f-4bd0-95fe-59e006b0b870
    authenticated = true
    local_addr = 172.30.2.5:443
    method = POST
    remote_addr = 172.20.17.106:54007
    req_id = 5390d360-c899-42c1-8004-d35275fd18d9
    resource = Fleet
    result = Ok(())
    uri = https://oxide.sys.rack2.eng.oxide.computer/v1/timeseries/query
21:07:41.187Z INFO 65a11c18-7f59-41ac-b9e7-680627f996e7 (dropshot_external): request completed
    error_message_external = Internal Server Error
    error_message_internal = Error interacting with telemetry database: Query failed: Code: 62. DB::Exception: Syntax error: failed at position 262134 ('968216818368'): 968216818368. Max query size exceeded: '968216818368'. (SYNTAX_ERROR) (version 23.8.7.1)\n
    file = /home/build/.cargo/git/checkouts/dropshot-a4a923d29dccc492/29ae98d/dropshot/src/server.rs:837
    latency_us = 707306
    local_addr = 172.30.2.5:443
    method = POST
    remote_addr = 172.20.17.106:54007
    req_id = 5390d360-c899-42c1-8004-d35275fd18d9
    response_code = 500
    uri = https://oxide.sys.rack2.eng.oxide.computer/v1/timeseries/query
```

We're constructing a list of timeseries keys that is quite large, since there are no filters other than time. So we try to give ClickHouse a huge list of keys, and hit their maximum query limit.

There are a few options here to avoid the 500. We can bail out on the query and convert it to a 400, asking the client to be more specific. Or we can break the actual list of timeseries keys we want into chunks, and effectively paginate that internally from ClickHouse.

### PR DESCRIPTION
**Pull request by bnaecker**
- Fixes #5405
- Limits the number of consistent keys used in one measurement query, to ensure we always fit within ClickHouse's SQL query size limit (256KiB). If the number of consistent keys in a single group exceeds some fraction of that, break those into chunks to stay under the limit.
- Adds tests for method chunking up the consistent key groups.

### CODE REVIEW

**Comment by bnaecker** [comment]
In addition to the actual tests I've added, I copied `oxdb` built from this commit to the Dogfood rack and run a query that was known to previously return a 500 from Nexus. This query completes without an error!

```
0x〉get crucible_upstairs:read | filter timestamp > @now() - 1d
....
   [2024-04-05 22:15:07.869765549, 2024-04-05 22:15:37.871406293]: [0]
   [2024-04-05 22:15:37.871406293, 2024-04-05 22:16:07.873002746]: [0]
   [2024-04-05 22:16:07.873002746, 2024-04-05 22:16:37.874688157]: [0]
   [2024-04-05 22:16:37.874688157, 2024-04-05 22:17:07.876804781]: [0]
   [2024-04-05 22:17:07.876804781, 2024-04-05 22:17:37.878024267]: [0]
   [2024-04-05 22:17:37.878024267, 2024-04-05 22:18:07.879784523]: [0]
   [2024-04-05 22:18:07.879784523, 2024-04-05 22:18:37.882220322]: [0]
```

**Review by david-crespo — APPROVED** [review]
Looks good! I wondered whether the built-in [`chunks`](https://doc.rust-lang.org/std/slice/struct.Chunks.html) method on slices might help, but it is not obvious how to do that with this object and it probably wouldn't be any simpler.

**Comment by bnaecker** [comment]
Yeah, I had hoped to use something like the  `chunks` method, but I don't think it works because we have two layers of containers here. We want to break based on the merged size of each of them. Actually! I wonder if we can `flatten()` and then call `chunks()`? That might work, and make things much simpler. Let me try it out.

**Comment by bnaecker** [comment]
Oh, I remember why I didn't do that either. The `ConsistentKeyGroup` isn't just a container, it also has an optional predicate. I can't see a clean way to chain the keys from each group; break them at our limit; and also include the predicates with each group.

I'll leave it as-is for now, thanks for the review!

**Pull request merged**
