### PR TITLE
omicron-package: use topological sort for nested composite package deps

### LINKED ISSUE #3582: Sporadic omicron-package failures creating sp-sim-softnpu.tar.gz
When running `omicron-package package` package recently, there are sporadic failures creating `sp-sim-softnpu.tar.gz`

```
Error: failed to create switch-softnpu in "out/"

Caused by:
    Missing gzip header from out/sp-sim-softnpu.tar.gz - cannot add it to zone image
*** Error code 1
```

Retrying (sometimes a few times) usually works.

### PR DESCRIPTION
**Pull request by luqmana**
Fixes #3582 hopefully.

### CODE REVIEW

**Review by iliana — APPROVED** [review]

**Comment by luqmana** [comment]
Also realized we were building `sp-sim` for `switch=asic` builds even though it's not actually needed.

**Review by smklein — APPROVED** [review]
This is great, and... so much more elegant than what I would have done. Thanks for adding this!

**Comment by davepacheco** [comment]
Does anybody happen to have the text of the error message that you'd get when running into this bug?

**Comment by luqmana** [comment]
> Does anybody happen to have the text of the error message that you'd get when running into this bug?

Something like what [ry ran into](https://github.com/oxidecomputer/omicron/issues/3582):
```
Error: failed to create switch-softnpu in "out/"

Caused by:
    Missing gzip header from out/sp-sim-softnpu.tar.gz - cannot add it to zone image
*** Error code 1
````

**Pull request merged**
