### PR TITLE
Sled agent should not use an anycast address

### PR DESCRIPTION
**Pull request by bnaecker**

### CODE REVIEW

**Comment by bnaecker** [comment]
For more context, the network address for an IPv6 `/64` subnet is technically reserved as an [anycast address](https://datatracker.ietf.org/doc/html/rfc4291#section-2.6.1). These are used to assign the same exact address to multiple interfaces, on multiple hosts, for things like routing to the "closest" service (in a routing sense). It likely won't matter, since all our sled underlay prefixes should be unique, but using this address _might_ confuse some of the higher-level routing protocols. It's probably best to avoid it, and easy to do so.

**Review by smklein — APPROVED** [review]
LGTM, but can you update https://github.com/oxidecomputer/omicron/blob/main/README.adoc#test-environment too?

**Comment by luqmana** [comment]
Did this also need to be updated? https://github.com/oxidecomputer/omicron/blob/442215a8283a4103ad13f57d15d1d31b64ffdccc/sled-agent/src/illumos/zone.rs#L432

That's currently how sled-agent gets an IPv6 address. Called here:
https://github.com/oxidecomputer/omicron/blob/72a44962573fc332edb7e142cd3aa4321da7c6ed/sled-agent/src/sled_agent.rs#L110

**Comment by bnaecker** [comment]
@luqmana That's a good question. I will test it now, but I don't understand what that subnet is doing. It's a `/16`, which is definitely unusual, and it's _not_ the address that the sled agent Dropshot server listens on. The comment implies this is required for the kernel to route traffic to the zones. That may be true, I don't know.

Thanks for flagging it, I'll see what shakes out.

**Comment by bnaecker** [comment]
Yes, this should be updated. I'm going to rework this slightly to accept the address as an argument, ultimately from the configuration file. We'll only have _two_ places the address is duplicated, rather than _three_, yay!

The address should have a `/64` prefix length too, not `/16`. The other addresses on the sled are all within the underlay prefix, by construction. Anything not in that prefix should be routed off the sled, i.e., through Sidecar. By providing a `/16` here, were telling the kernel that it should expect to find any address within the entire `fd00:1de` prefix as a directly connected neighbor, on the same L2 segment, which is not accurate.

**Comment by bnaecker** [comment]
This should be fixed in #887, thanks @luqmana for catching it!

**Pull request merged**
