### PR TITLE
dedup progenitor, and update crucible and propolis revs

### PR DESCRIPTION
**Pull request by sunshowers**
This is PR 3 of N in this series. For the earlier ones, see:

* https://github.com/oxidecomputer/crucible/pull/552
* https://github.com/oxidecomputer/propolis/pull/262

Currently, we specify the progenitor dependency as both:

```toml
progenitor-client = { git = "https://github.com/oxidecomputer/progenitor", branch = "main" }
```

And

```toml
progenitor-client = { git = "https://github.com/oxidecomputer/progenitor" }
```

Cargo (due to https://github.com/rust-lang/cargo/issues/7497) doesn't dedup these dependencies even
though they resolve to the same branch and hash. This causes issues with
`cargo doc` colliding with itself, as it tries to document both:

```
Documenting progenitor-impl v0.2.1-dev (https://github.com/oxidecomputer/progenitor#4b5cef4b)
Documenting progenitor-impl v0.2.1-dev (https://github.com/oxidecomputer/progenitor?branch=main#4b5cef4b)
```

Fix this by always using the branch name. (We choose this option over
not specifying the branch so to maintain uniformity in cases where a
non-default branch must be used.)

This also requires a crucible update, since that didn't specify a branch
either. And the crucible update necessitates a propolis update to get the versions aligned.

In the future it would be nice to have a lint which ensures that git
dependencies always have the branch name in them.

### CODE REVIEW

**Comment by sunshowers** [comment]
This is going to need https://github.com/oxidecomputer/propolis/pull/262 as well.

**Review by leftwo — COMMENTED** [review]
You will also need to update the packaging side as well, with new links to the CI produced 
archives for propolis and crucible, as we want the compiled Omicron to match the tar.gz file that becomes part of the installed image.

Check out the `package-manifest.toml` file for details.
You will have to wait for both crucible and propolis to finish their CI runs on main/master before you will be able to get the zip archive and SHA hash needed here.

**Review by ahl — COMMENTED** [review]
looks good

**Comment by zephraph** [comment]
Is the helios failure just a flake?

**Comment by sunshowers** [comment]
> Is the helios failure just a flake?

I think it might be genuine. I'm not entirely sure. I'm going to dig into it later today.

**Comment by luqmana** [comment]
Looks like https://github.com/bytecodealliance/rustix/issues/467

**Comment by sunshowers** [comment]
Ah OK, that's easy enough to patch in omicron. Will put up a fix for it.

**Review by luqmana — APPROVED** [review]
Thanks!

**Pull request merged**
