### PR TITLE
Bring in fix for opte#267

### PR DESCRIPTION
**Pull request by rzezeski**

### CODE REVIEW

**Comment by rzezeski** [comment]
@Nieuwejaar when this lands you should be able to run omicron+opte on DEBUG again without issue.

**Comment by bnaecker** [comment]
Looks like you'll need to run a `cargo build` locally or something similar to update the lockfile for CI.

**Comment by rzezeski** [comment]
@jclulow We need to bump the image for `helios/deploy` again. When you get a moment do you mind hitting pushing the correct buttons?

**Review by bnaecker — APPROVED** [review]

**Comment by jclulow** [comment]
> @jclulow We need to bump the image for `helios/deploy` again. When you get a moment do you mind hitting pushing the correct buttons?

Done, with my apologies for the delay!

**Pull request merged**
