### PR TITLE
Add ClickhouseAdmin to internal DNS

### PR DESCRIPTION
**Pull request by andrewjstone**

### CODE REVIEW

**Review by bnaecker — APPROVED** [review]
Looks good to me!

**Comment by andrewjstone** [comment]
Welp, as discussed in chat, we actually need a separate SRV record to distinguish between `clickhouse-admin` running in the keeper and server zones. Since the API is disjoint for each zone, we really should split `clickhouse-admin` into two separate dropshot servers. I'll open an issue for that.

**Comment by andrewjstone** [comment]
I opened an issue related to separate servers: https://github.com/oxidecomputer/omicron/issues/6779

**Comment by andrewjstone** [comment]
> Welp, as discussed in chat, we actually need a separate SRV record to distinguish between `clickhouse-admin` running in the keeper and server zones. Since the API is disjoint for each zone, we really should split `clickhouse-admin` into two separate dropshot servers. I'll open an issue for that.

Separate SRV records added in [f4fe7c4](https://github.com/oxidecomputer/omicron/pull/6777/commits/f4fe7c4ac425577ecbce60311add5da8b161e41f).

Separating the `ClickhouseAdmin` server itself is left as a follow up.

**Pull request merged**
