### PR TITLE
update crucible and propolis images

### PR DESCRIPTION
**Pull request by jmpesp**
pull in latest crucible image to grab the volume ownership fix from
https://github.com/oxidecomputer/crucible/pull/287

### CODE REVIEW

**Review by smklein — APPROVED** [review]
Assuming the API is unchanged - because we're still using the old bindings, in our `Cargo.toml` dependencies - this LGTM

**Comment by jmpesp** [comment]
> Assuming the API is unchanged - because we're still using the old bindings, in our `Cargo.toml` dependencies - this LGTM

This is a good point, updated Cargo revs too in 41f695f8.

Actually I'll also have to update propolis (which is where the upstairs runs!), which I'm doing now. That should go in together with this so that both images change with the same commit.

**Comment by jmpesp** [comment]
opened https://github.com/oxidecomputer/propolis/pull/118

**Comment by jmpesp** [comment]
> opened [oxidecomputer/propolis#118](https://github.com/oxidecomputer/propolis/pull/118)

this was merged, waiting on images to be built

**Comment by jmpesp** [comment]
https://github.com/oxidecomputer/crucible/pull/292 should fix those `failed to select a version for `tracing`` errors, waiting for next crucible images to build

**Comment by jmpesp** [comment]
turns out it does not, because propolis still pulls in the old crucible. https://github.com/oxidecomputer/propolis/pull/121 opened to fix...

**Pull request merged**
