### PR TITLE
convert route endpoints to new lookup API

### PR DESCRIPTION
**Pull request by davepacheco**
This change updates the "route" endpoints to use the new lookup API.

As part of this, I changed the `router_id` column on the `router_route` table to be called `vpc_router_id`, so that we can maintain the expectation that the foreign key id is derivable from the foreign table name.  #798 depends on this.

### CODE REVIEW

**Comment by davepacheco** [comment]
I think this is ready to review but it's blocked on #798.

**Review by david-crespo — APPROVED** [review]
Looks great. Kind of funny that it's _more_ code, but it's very nice code. And deleting `vpc_router_lookup_by_path` eventually will offset it.

**Comment by davepacheco** [comment]
Yeah, I'd forgotten to remove `vpc_router_lookup_by_path`.  It's less code now!

**Comment by david-crespo** [comment]
> [oh right, we can remove the hand-written database functions now](https://github.com/oxidecomputer/omicron/pull/839/commits/386549a38969594d4b5372cbaf9725a0f96df18e)

never mind about it being more code!

**Comment by zephraph** [comment]
This is just sooo damn good.

**Pull request merged**
