### PR TITLE
stop building rot-prod-rel/rot-staging-dev repos

### PR DESCRIPTION
**Pull request by iliana**

### CODE REVIEW

**Comment by iliana** [comment]
Seems like it worked first try?

<details><summary>Diffing the tufaceous manifests from #5313 and this run</summary>

Looks like we don't sort the list of zones, heh. But everything seems to be there.

```diff
$ diff -u 5313-manifest.toml 5316-manifest.toml
--- 5313-manifest.toml  2024-03-23 12:15:47
+++ 5316-manifest.toml  2024-03-23 12:15:42
@@ -1,52 +1,52 @@
-system_version = "7.0.0-0.ci+git26fad698030"
+system_version = "7.0.0-0.ci+gitb4e1a285ef8"

 [[artifact.control_plane]]
 name = "control-plane"
-version = "7.0.0-0.ci+git26fad698030"
+version = "7.0.0-0.ci+gitb4e1a285ef8"
 [artifact.control_plane.source]
 kind = "composite-control-plane"
 [[artifact.control_plane.source.zones]]
 kind = "file"
-path = "/work/package/install/oximeter.tar.gz"
+path = "/work/package/install/crucible.tar.gz"
 [[artifact.control_plane.source.zones]]
 kind = "file"
-path = "/work/package/install/ntp.tar.gz"
+path = "/work/package/install/external_dns.tar.gz"
 [[artifact.control_plane.source.zones]]
 kind = "file"
-path = "/work/package/install/internal_dns.tar.gz"
+path = "/work/package/install/clickhouse_keeper.tar.gz"
 [[artifact.control_plane.source.zones]]
 kind = "file"
 path = "/work/package/install/cockroachdb.tar.gz"
 [[artifact.control_plane.source.zones]]
 kind = "file"
-path = "/work/package/install/crucible.tar.gz"
+path = "/work/package/install/crucible_pantry.tar.gz"
 [[artifact.control_plane.source.zones]]
 kind = "file"
-path = "/work/package/install/external_dns.tar.gz"
+path = "/work/package/install/oximeter.tar.gz"
 [[artifact.control_plane.source.zones]]
 kind = "file"
-path = "/work/package/install/clickhouse_keeper.tar.gz"
+path = "/work/package/install/clickhouse.tar.gz"
 [[artifact.control_plane.source.zones]]
 kind = "file"
-path = "/work/package/install/clickhouse.tar.gz"
+path = "/work/package/install/internal_dns.tar.gz"
 [[artifact.control_plane.source.zones]]
 kind = "file"
 path = "/work/package/install/probe.tar.gz"
 [[artifact.control_plane.source.zones]]
 kind = "file"
-path = "/work/package/install/crucible_pantry.tar.gz"
+path = "/work/package/install/nexus.tar.gz"
 [[artifact.control_plane.source.zones]]
 kind = "file"
-path = "/work/package/install/nexus.tar.gz"
+path = "/work/package/install/ntp.tar.gz"
 [[artifact.host]]
 name = "host"
-version = "7.0.0-0.ci+git26fad698030"
+version = "7.0.0-0.ci+gitb4e1a285ef8"
 [artifact.host.source]
 kind = "file"
 path = "/input/host/work/helios/upload/os-host.tar.gz"
 [[artifact.trampoline]]
 name = "trampoline"
-version = "7.0.0-0.ci+git26fad698030"
+version = "7.0.0-0.ci+gitb4e1a285ef8"
 [artifact.trampoline.source]
 kind = "file"
 path = "/input/host/work/helios/upload/os-trampoline.tar.gz"
```

</details>

**Comment by jclulow** [comment]
FWIW, I've spent some time this weekend closing out oxidecomputer/buildomat#31.  We now support HTTP range gets on files (see example testing with `curl -C -` in that ticket).

I've also finally figured out how to actually log what happens while transferring the body of a response, and implement log messages that include detailed information about the transfer (see oxidecomputer/buildomat#36).  This should include information about whose fault we think an interruption is: did it happen on the downstream client side, or did it happen with the backend where we've stored the large file.

Could we try combining the split ZIP file into one slightly larger file in this PR?  I haven't been able to reproduce the large file download issue myself lately, and we now have telemetry to investigate it if it recurs -- and it shouldn't be crippling, because `curl -C -` works for resuming the download and is easy to include in any scripts we have that download large files.

**Review by labbott — APPROVED** [review]
LGTM! I'm going to use this as a reference for the work I'm doing.

**Comment by iliana** [comment]
> Could we try combining the split ZIP file into one slightly larger file in this PR?

I am tempted to hold off on this until we have the v7 release out the door, as to not break tooling that expects the parta/partb files while we're in a time crunch to get things on rack2/rack3. I am not sure how much of a concern this is in reality though. We could discuss in the dogfood channel?

**Comment by iliana** [comment]
Going to go ahead and merge this as-is, and write up a PR to stop doing the split post-v7.

**Pull request merged**
