### PR TITLE
add API endpoint for BGP announce set modification

### LINKED ISSUE #6022: Cannot modify BGP announce sets
Once a BGP announce set has been created, it cannot be modified without deleting and recreating it. Deletion will cause the withdrawal of existing prefixes, which can lead to API unavailability and the inability to recreate.

### PR DESCRIPTION
**Pull request by rcgoodfellow**
Fixes #6022

### CODE REVIEW

**Comment by rcgoodfellow** [comment]
Basic testing performed in a4x2 and things work as expected.

**Comment by david-crespo** [comment]
What's the difference between create and update if they take the same body?

**Comment by rcgoodfellow** [comment]
> What's the difference between create and update if they take the same body?

- If the announce set does not exist, nothing.
- If the announce set exists, but is empty, nothing.
- If the announce set exists, and the update is purely additive, nothing.
- If the announce set exists, and the update is not purely additive, then create will not remove existing entries, but update will.

More concisely, the update is a complete specification, and the announce set will match the request payload exactly on successful return, whereas a create can only add entries. I think for create, we may want to consider returning an error code if the announce set already exists.

**Comment by david-crespo** [comment]
Ok. I think that should be added as description in the doc comment on on each endpoint. Something like "Replaces existing announce set with the one specified." and "Adds new entries but does not modify existing ones." That mostly solves the issue in the following musings, so take them however you want.

The names update and create are a little counterintuitive to me for these operations — update less so than create. Update here works similarly to updating a project or whatever: you expect the state after the request to match what you passed in. "Create" is worse because when I see "create set" I expect it to create a set, not union the existing set with what I pass in. 

Erroring if the set already exists _would_ fix that, but that also means the functionality of create is a subset of update (I think), which makes me wonder whether we really need both. It seems like we could do ok with just update. That's the model we follow for firewall rules, though I admit it's is kind of a pain and requires shenanigans in the client to simulate adding one rule at a time.

**Comment by rcgoodfellow** [comment]
>  Something like "Replaces existing announce set with the one specified."

Done

>  It seems like we could do ok with just update

So say we all.

**Review by david-crespo — APPROVED** [review]

**Pull request merged**
