### PR TITLE
Pin qorb's revision

### PR DESCRIPTION
**Pull request by smklein**
I'd like to integrate https://github.com/oxidecomputer/qorb/pull/45 into qorb, and then omicron, but I want to be able to control that revision explicitly.

Before I do that, pin the revision of qorb we're using so that "merging something into qorb" doesn't break omicron.

### CODE REVIEW

**Comment by sunshowers** [comment]
Thanks. Are you sure this is a good idea? Because it means that if non-Omicron workspaces depend on a different revision of qorb it might become hard to reconcile that with Omicron -- you'll have two copies of qorb floating around. Using `main` avoids these problems.

**Comment by smklein** [comment]
I thought that if I specified "use the master branch" in cargo.toml, and then manually tried to update cargo.lock, that change to the lockfile would get overwritten the next time someone tries to build?

My concern is that if I commit a breaking change to qorb it'll immediately break omicron's build

**Comment by smklein** [comment]
I could also just start publishing / using published versions of qorb?

**Comment by smklein** [comment]
> I could also just start publishing / using published versions of qorb?

Hrm, okay, can't do this without updating `diesel-dtrace`, where we also seem to be using the `main` branch

**Comment by smklein** [comment]
I published a new revision of `diesel-dtrace` and `qorb`, and I'm using them here now.

**Comment by sunshowers** [comment]
> I thought that if I specified "use the master branch" in cargo.toml, and then manually tried to update cargo.lock, that change to the lockfile would get overwritten the next time someone tries to build?

Only if something causes the update to happen -- in general, the git repo being updated by itself won't cause a local update. In your case I guess you bumped another dependency which caused it?

> My concern is that if I commit a breaking change to qorb it'll immediately break omicron's build

No, this won't happen automatically.

**Review by sunshowers — APPROVED** [review]
This definitely works!

I'd recommend publishing qorb 0.1.0 soon btw, 0.0.x versions being unable to be patched has caused a lot of problems for me in the past.

**Pull request merged**
