### PR TITLE
Bump system version to 1.0.4

### PR DESCRIPTION
**Pull request by iliana**
In preparation for the next release, bump the system version.

### CODE REVIEW

**Review by askfongjojo — APPROVED** [review]

**Review by leftwo — APPROVED** [review]

**Comment by iliana** [comment]
I realized a few hours ago that this change does have the effect of also bumping all our control plane component versions to "4.0.0". This is probably not ideal.

I might prefer to change this to keep the version stamped into zones and whatnot at the current version, and replace the system version in the tuf-repo.sh job.

**Comment by askfongjojo** [comment]
How about we make it v1.0.4 first? It should not result in confusion as long as we are good about linking this to the marketing version in our internal documentation.

**Comment by iliana** [comment]
As in, control plane components versioned v1.0.4, while still adjusting the system version to v4.0.0?

**Comment by askfongjojo** [comment]
Sorry for being unclear. Just bumping the system version to 1.0.4, exactly like how we did it for 1.0.3.

**Comment by iliana** [comment]
OK. I'll adjust this PR and we'll work out the finer details.

**Comment by askfongjojo** [comment]
For the record - LGTM after all the back-and-forth.

**Pull request merged**
