### PR TITLE
Add policy to the db

### PR DESCRIPTION
**Pull request by andrewjstone**
Still need to add queries and usage.

### CODE REVIEW

**Comment by david-crespo** [comment]
We have a lot of policies — what do you think about adding a qualifier to the name of the table and the model to indicate what it is a policy for?

**Comment by andrewjstone** [comment]
> We have a lot of policies — what do you think about adding a qualifier to the name of the table and the model to indicate what it is a policy for?

:) That's part of the problem I'm having. You can read my soliloquy in the #oxide-update channel, but the short form is that 
I don't believe there is a good qualifier for it. Right now it's the "rack policy", but in the future it will be the "AZ" or "Region" or "Cell" policy. I suppose I can just call it `rack_policy` for now, as that's the most correct, and I completely agree with you that `policy` is too generic.

**Comment by david-crespo** [comment]
Rack policy for what?

**Comment by andrewjstone** [comment]
> Rack policy for deciding what?

I changed it to `reconfigurator_policy` as discussed in chat. Thanks for the feedback @david-crespo.

**Comment by andrewjstone** [comment]
Closing in favor of #6862

**Pull request closed without merging**
