### PR TITLE
Update Clickhouse to 22.8.9.24-lts

### PR DESCRIPTION
**Pull request by karencfv**
Closes: https://github.com/oxidecomputer/omicron/issues/3447

Ran several manual tests as well and everything seemed fine, looks like no code changes were necessary.

### CODE REVIEW

**Comment by karencfv** [comment]
gargh, macos is complaining, finding a fix

**Comment by karencfv** [comment]
I spent several hours trying to get a properly signed macos build and failed miserably. With the time pressures for FCS, the fact the macos build is only used for simulated omicron, and that there are really no breaking changes that are relevant to our setup between the two versions. I'm inclined to leaving the macos update for a later date.

**Comment by karencfv** [comment]
@bnaecker @smklein , I'm assuming we've never updated ClickHouse during a mupdate. Is there a specific process we need to follow? How much of this is already automated?

Doc on updating -> https://clickhouse.com/docs/en/operations/update

**Comment by bnaecker** [comment]
I don't believe we've updated either database during a mupdate, no. I have no idea how that will work. Is the new version able to read the database files for the older one? If so, and if the API is the same as far as our client is concerned (which looks to be the case given that CI is passing), then it seems like it might be fine to just replace the binary.

**Review by bnaecker — APPROVED** [review]
Seems OK on the face of it. It would be really nice to see what happens when updating on a live system before merging this, if that's possible.

**Comment by karencfv** [comment]
Thanks. Yeah, you're right, I'll run further tests with updating before merging

**Comment by karencfv** [comment]
I ran some tests locally and the update worked with a few caveats. Just stopping, updating and restarting the database does not work. 

At first I just assumed that I'd have to restart Oximeter (due to service discovery perhaps?), but that did not work. Oximeter was able to connect to Clickhouse and created the database/tables but was not receiving metrics from Nexus.

After that, I decided to restart both Oximeter and Nexus and that worked, database/tables created and was receiving metrics from Nexus.

For now this is fine I guess, since from what I learned everything will wiped out before installing on dog food. Once data replication (https://github.com/oxidecomputer/omicron/issues/2158) has been implemented, we'll have to work on making sure oximeter can find the newly updated clickhouse instances and we don't loose any data on update.

I'm working half a day today but @citrus-it (thanks Andy!) volunteered to try out the update on dogfood tomorrow.

I'll hold off on merging this PR until then

**Comment by citrus-it** [comment]
I did an in-place upgrade on dogfood and that seemed to work fine.

```
clickhouse# cd /opt/oxide
clickhouse# ls
clickhouse/                            clickhouse-v22.8.9.24.illumos.tar.gz
clickhouse-v21.7.1.1/                  lib/
clickhouse-v22.8.9.24/
clickhouse# ./clickhouse/clickhouse server -V
ClickHouse server version 21.7.1.1.
clickhouse# svcs clickhouse
STATE          STIME    FMRI
online         Jun_28   svc:/oxide/clickhouse:default
clickhouse# zfs list /data
NAME                                                  USED  AVAIL     REFER  MOUNTPOINT
oxp_c861c6c4-eaf9-459d-8348-b1eaf9129385/clickhouse   466M  2.80T      466M  /data
clickhouse#
clickhouse# svcadm disable -s clickhouse
clickhouse# pgrep click

clickhouse# zfs snapshot oxp_c861c6c4-eaf9-459d-8348-b1eaf9129385/clickhouse@v21.7.1.1
clickhouse# rsync -avr clickhouse-v22.8.9.24/ clickhouse/

clickhouse# ./clickhouse/clickhouse server -V
ClickHouse server version 22.8.9.1.

clickhouse# svcadm enable -s clickhouse
clickhouse# /opt/oxide/clickhouse/clickhouse client -h fd00:1122:3344:102::7
ClickHouse client version 22.8.9.1.
Connecting to fd00:1122:3344:102::7:9000 as user default.
Connected to ClickHouse server version 22.8.9 revision 54460.

oxz_clickhouse_oxp_c861c6c4-eaf9-459d-8348-b1eaf9129385 :) show databases;

SHOW DATABASES

Query id: b57906ea-6aaf-493d-81db-902c9c0ae5fb

┌─name───────────────┐
│ INFORMATION_SCHEMA │
│ default            │
│ information_schema │
│ oximeter           │
│ system             │
└────────────────────┘

5 rows in set. Elapsed: 0.001 sec.
```

Everything came back into life by itself - the nexus and oximeter logs show that processing is occurring, the console shows metrics (including historical ones) and changes when instances are created and deleted.

**Comment by karencfv** [comment]
Thanks @citrus-it! So happy it worked flawlessly on the dogfood rack. I'll merge this and thanks again Andy for the help with this issue :bowing_woman:

**Pull request merged**
