### PR TITLE
bump dendrite/maghemite

### PR DESCRIPTION
**Pull request by rcgoodfellow**
### Dendrite

- oxidecomputer/dendrite#355
- oxidecomputer/dendrite#344
- oxidecomputer/dendrite#333
- oxidecomputer/dendrite#340

### Maghemite
- oxidecomputer/maghemite#61
- oxidecomputer/maghemite#66

### CODE REVIEW

**Review by jmpesp — APPROVED** [review]

**Comment by jclulow** [comment]
FWIW, the % prefix allows the files to change while they're being uploaded.  What error did you see from buildomat?

**Comment by rcgoodfellow** [comment]
You can see the error in [this](https://github.com/oxidecomputer/omicron/runs/13807983531) run. It looks like the propolis log file disappeared out from under the artifact collection.

**Comment by rcgoodfellow** [comment]
Pulling in @internet-diglett to look at the rack initialize changes.

**Comment by internet-diglett** [comment]
@rcgoodfellow looks good to me!

**Review by internet-diglett — APPROVED** [review]

**Pull request merged**
