### PR TITLE
Trigger inventory collection on sled add

### PR DESCRIPTION
**Pull request by andrewjstone**
This is based on discussion in https://github.com/oxidecomputer/omicron/issues/5058

I'm still testing it.

### CODE REVIEW

**Comment by andrewjstone** [comment]
Seems to work.

Before and after adding a sled. Look at the last timestamp.

```
root@oxz_switch:~# omdb db inventory collections list
note: database URL not specified.  Will search DNS.
note: (override with --db-url or OMDB_DB_URL)
note: using DNS server for subnet fd00:1122:3344::/48
note: (if this is not right, use --dns-server to specify an alternate DNS server)
note: using database URL postgresql://root@[fd00:1122:3344:101::3]:32221,[fd00:1122:3344:102::4]:32221,[fd00:1122:3344:103::3]:32221,[fd00:1122:3344:101::4]:32221,[fd00:1122:3344:102::3]:32221/omicron?sslmode=disable
note: database schema version matches expected (33.0.1)
ID                                   STARTED              TOOK   NSPS NERRORS
2ae5c857-308e-4c36-95ed-d2bfae0ba55e 2024-02-14T20:45:08Z 124 ms 5    0
dd2b55d9-49d3-4707-8fcd-c1d3b2600a3d 2024-02-14T20:45:08Z 169 ms 5    0
1e7efbdf-e711-4df8-a54a-5f70633fe709 2024-02-14T20:45:10Z 107 ms 5    0
11c5e0ef-1fea-46f4-96b6-32864db27578 2024-02-14T20:45:46Z 127 ms 5    0
root@oxz_switch:~# date
Wed Feb 14 20:49:26 UTC 2024
root@oxz_switch:~# omdb db inventory collections list
note: database URL not specified.  Will search DNS.
note: (override with --db-url or OMDB_DB_URL)
note: using DNS server for subnet fd00:1122:3344::/48
note: (if this is not right, use --dns-server to specify an alternate DNS server)
note: using database URL postgresql://root@[fd00:1122:3344:101::3]:32221,[fd00:1122:3344:102::4]:32221,[fd00:1122:3344:103::3]:32221,[fd00:1122:3344:101::4]:32221,[fd00:1122:3344:102::3]:32221/omicron?sslmode=disable
note: database schema version matches expected (33.0.1)
ID                                   STARTED              TOOK   NSPS NERRORS
dd2b55d9-49d3-4707-8fcd-c1d3b2600a3d 2024-02-14T20:45:08Z 169 ms 5    0
1e7efbdf-e711-4df8-a54a-5f70633fe709 2024-02-14T20:45:10Z 107 ms 5    0
11c5e0ef-1fea-46f4-96b6-32864db27578 2024-02-14T20:45:46Z 127 ms 5    0
bc9713c8-bd73-4041-bd32-1f49a1d7eca7 2024-02-14T20:49:47Z 232 ms 5    0
```

**Comment by andrewjstone** [comment]
Yup, and I can generate a blueprint with it.

**Review by davepacheco — APPROVED** [review]
Looks good!

Just wondering: is the `sled_add` call right above this synchronous -- i.e., do we expect that the sled agent should already be running when it returns?  If not, this won't necessarily work (though it won't hurt either).  In that case, maybe the thing to do would be put this call in the internal API call where we upsert a sled, if the sled appears to be one we didn't previously know about.  That might be a good idea anyway.  But if this works, no need to change it for this PR.

**Comment by andrewjstone** [comment]
> Looks good!
> 
> Just wondering: is the `sled_add` call right above this synchronous -- i.e., do we expect that the sled agent should already be running when it returns? If not, this won't necessarily work (though it won't hurt either). In that case, maybe the thing to do would be put this call in the internal API call where we upsert a sled, if the sled appears to be one we didn't previously know about. That might be a good idea anyway. But if this works, no need to change it for this PR.

That's a great question @davepacheco. The `sled_add` call is indeed synchronous and doesn't return until the sled-agent server is started. The behavior is the same as in RSS and doesn't return until this call is complete: https://github.com/oxidecomputer/omicron/blob/main/sled-agent/src/bootstrap/server.rs#L354

Because this is true and it worked on testing, gonna go ahead and merge. Thanks for the quick review!

**Pull request merged**
