### PR TITLE
[installinator] Functional bootstrap networking 

### PR DESCRIPTION
**Pull request by jgallagher**
This PR contains mostly changes to `sled-agent` to support `installinator` connecting to `wicketd` over the bootstrap network. Highlighting the most significant commits:

1. Move enabling of ipv6-forwarding earlier (from sled-agent to bootstrap-agent): 59fe9c16f1503e3b0c83c6fd4743aecd1c32ba1b
2. Add the proper route in the switch zone to enable its bootstrap address: 625011346e73f0ee5575baa07fbebe621622d4f4, which builds on the commits immediately prior to it that do some work in `illumos-utils` to let us get the link-local address we need
3. Bumps to the latest maghemite to pick up the changes made in https://github.com/oxidecomputer/maghemite/pull/58
4. Replaces calls to `bootstrap_ip(..., 1)` and `bootstrap_ip(..., 2)` with `BootstrapInterface::GlobalZone.ip(...)` and `BootstrapInterface::SwitchZone.ip(...)`: ac752c71eaaa8945ff6998833355ab1482fb4348
5. Extends the ddm client `get_peers()` helper function to take a list of `BootstrapInterface`s the caller wants: `installinator` wants to find both gz and switch zone peers; `sled-agent` only wants to find gz peers

Edit: Two additional bugfixes based on chat and @andrewjstone's experience:

1. RSS should talk to its localhost mg-ddm, not its switch zone mg-ddm (since only scrimlets will have a switch zone: [b845621](https://github.com/oxidecomputer/omicron/pull/2939/commits/b8456218eb167e06a7328f8a94eaeb012f49ea97)
2. Rename `DdmAdminClient::get_peers()` to `DdmAdminClient::derive_bootstrap_addrs_from_prefixes`: [ea19f9c](https://github.com/oxidecomputer/omicron/pull/2939/commits/ea19f9c658939480088f97b4c7edc6a8b3840d99)

### CODE REVIEW

**Review by jmpesp — APPROVED** [review]
Looks good, and the my cluster still assembles :) I wonder if we need the ddm client `Client::switch_zone` constructor anymore?

**Comment by andrewjstone** [comment]
This PR also solved my networking woes from yesterday.

**Comment by jgallagher** [comment]
> Looks good, and the my cluster still assembles :) I wonder if we need the ddm client `Client::switch_zone` constructor anymore?

Turns out there was one remaining use, similarly incorrect I believe (related to trust quorum, which also needs to happen on non-scrimlets). I removed that use and the `DdmAdminClient::{switch_zone,address}` constructors in [d045475](https://github.com/oxidecomputer/omicron/pull/2939/commits/d045475d1f124fbb04db6ff43805cb59592631bb).

**Comment by jmpesp** [comment]
:rocket:

**Pull request merged**
