### PR TITLE
test proving that duplicate roles in PUT body trigger 500

### PR DESCRIPTION
**Pull request by david-crespo**

### CODE REVIEW

**Comment by david-crespo** [comment]
Amusingly, fleet alone does not have this problem.

```
test integration_tests::role_assignments::test_role_assignments_fleet ... FAILED
test integration_tests::role_assignments::test_role_assignments_organization ... ok
test integration_tests::role_assignments::test_role_assignments_project ... ok
test integration_tests::role_assignments::test_role_assignments_silo ... ok
```

**Comment by davepacheco** [comment]
> Fleet probably has this problem too, but something strange is going on. It 500s on the added dupes request as expected, but then the subsequent GET seems to be 403ing. So it seems something exciting is happening before that 500.

Was it a 403 _before_ the policy change as well?

**Comment by david-crespo** [comment]
I don't think it could be, because the tests passes without my added PUT with dupes.

**Comment by david-crespo** [comment]
Closing because this doesn't need to be open to serve its purpose!

**Pull request closed without merging**
