### PR TITLE
a few updates to get things to come up in a4x2

### PR DESCRIPTION
**Pull request by rcgoodfellow**

### CODE REVIEW

**Review by Nieuwejaar — COMMENTED** [review]
I have the database fix in my workspace, but I'm happy to just pull it from here.  

Do you know how the opte/buildomat relationship is managed?  Presumably Josh would update the buildomat systems, but that would break everybody else.  So, it seems like the OPTE update should go straight to the main branch, where everybody else can get it.

**Comment by FelixMcFelix** [comment]
> Do you know how the opte/buildomat relationship is managed? Presumably Josh would update the buildomat systems, but that would break everybody else. So, it seems like the OPTE update should go straight to the main branch, where everybody else can get it.

I have this OPTE update tee-d up in #5602 (since device teardown is now pretty different in a breaking way). It's currently waiting on the open lab ticket for a `lab-2.0-opte-0.31` image to be built. I think @jclulow still has to do this manually, but creation of a new image doesn't break `main` since each is pinned to an exact OPTE version.

**Comment by rcgoodfellow** [comment]
The maghemite being used in this branch depends on OPTE API version 31, so I think one way or another OPTE needs to be pulled in here, or we explicitly roll back maghemite which seems less appealing.

**Comment by rcgoodfellow** [comment]
Since #5602 has landed, once the `vlan` branch is rebased, this PR becomes obviated. Closing.

**Pull request closed without merging**
