### PR TITLE
Reduce 'test_projects_list' length

### PR DESCRIPTION
**Pull request by smklein**
I believe we still have coverage of pagination with smaller constants, and this prevents the test from taking 60+ seconds on my development machine.

### CODE REVIEW

**Review by david-crespo — APPROVED** [review]

**Comment by davepacheco** [comment]
Is it worth digging into why it's taking 60 seconds?  I think that's a lot slower than when the test was integrated.

If everything is working as intended, I would think we'd spend most of our time waiting on fsync in CockroachDB.  I've wondered whether we should run CockroachDB from a ZFS dataset with `sync=disabled`, or maybe set some equivalent option in CockroachDB.  It feels like we don't need crash-safety in the standard automated test suite.  It feels like this might significantly improve overall test time.  I can try this tomorrow.

**Comment by davepacheco** [comment]
For what it's worth, on a default dataset:

```
$ time cargo test -p omicron-nexus
...
real    3m27.083s
user    3m6.491s
sys     0m41.068s
```

With sync=disabled:

```
$ pfexec zfs create -o sync=disabled rpool/dangerzone
$ pfexec chown dap /rpool/dangerzone/
$ time TMPDIR=/rpool/dangerzone cargo test -p omicron-nexus
...
real    1m51.151s
user    2m51.598s
sys     0m36.310s
```

**Comment by davepacheco** [comment]
This particular test (as run with `time cargo test -p omicron-nexus --test=test_basic -- test_projects_list` goes from:

```
$ time cargo test -p omicron-nexus --test=test_basic -- test_projects_list
    Finished test [unoptimized + debuginfo] target(s) in 0.26s
     Running tests/test_basic.rs (target/debug/deps/test_basic-3577efb6c59515f9)

running 1 test
test test_projects_list has been running for over 60 seconds
test test_projects_list ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 3 filtered out; finished in 88.49s


real    1m28.882s
user    1m9.849s
sys     0m13.221s
```

to:


```
$ time TMPDIR=/rpool/dangerzone cargo test -p omicron-nexus --test=test_basic -- test_projects_list
    Finished test [unoptimized + debuginfo] target(s) in 0.27s
     Running tests/test_basic.rs (target/debug/deps/test_basic-3577efb6c59515f9)

running 1 test
test test_projects_list ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 3 filtered out; finished in 49.96s


real    0m50.354s
user    1m3.837s
sys     0m10.522s
```

which is nice, but 50s still sucks.

**Comment by smklein** [comment]
@davepacheco if I'm interpreting that analysis correctly:

- Changing ZFS sync options may help performance across all CRDB-backed tests
- This change is still worth having (independently) - even with the changed sync options, this test is proooobably doing more work than it needs to.

Is that right?

**Comment by davepacheco** [comment]
@smklein What if we parallelized the creation of Projects instead?

**Comment by smklein** [comment]
> @smklein What if we parallelized the creation of Projects instead?

I'd be on board with that direction too, but is this *supposed* to be a stress test? What do we gain by testing 1000 projects instead of 10?

I figured this was supposed to be a minimal integration test for pagination, and figured smaller/simpler would be better, as long as the coverage is the same.

**Comment by davepacheco** [comment]
> I'd be on board with that direction too, but is this supposed to be a stress test? What do we gain by testing 1000 projects instead of 10?

Imagine we mess up the implementation such that every query fetches _all_ projects, then picks out only the ones that are supposed to be on that page.  (That's easy to do with a traditional limit/offset model, or if one forgets the `ORDER BY` on the SQL query, or if one forgets the index.)  This is a scalability disaster.  With 10 projects, we'll never notice it.  With 1000 projects, we might notice the test performing pathologically and dig into it.  This obviously isn't a great long-term approach to scalability testing, but it felt like better than nothing when I wrote it.

**Comment by smklein** [comment]
Now that I integrated a benchmarking library into Omicron, maybe we could consider adding back a separate, explicitly performance-analyzing test along those lines, which acts as a stress test?

I still think it's worthwhile having this *integration* test be as fast as reasonably possible - letting "tests of scalability" conflate with integration / unit tests seems like it'll inevitably result in a slow test suite.

**Pull request merged**
