### PR TITLE
ci/tuf-repo: also create a repo for PVT1 hardware

### PR DESCRIPTION
**Pull request by iliana**
Draft mode for now, as this will conflict with #3437 and I will need to rebase onto that.

For the sake of keeping wicket-driven updates simple, our TUF repo zips only contain one revision of each image. However, the dogfood rack and the ~~DVT1~~ PVT1 rack have different board revisions, which means we need different SP images.

I'm currently led to believe these board revs are correct for ~~DVT1~~ PVT1:
- Gimlet rev D
- Sidecar rev C
- PSC rev C

This produces a repo-pvt1.zip with these revisions alongside repo-dogfood.zip. (I also changed the `[[publish]]` URLs, using "series" to refer to whatever we've named a collection of board revisions.)

**Also note**: This has the effect of moving Hubris from https://github.com/oxidecomputer/hubris/commit/b7529859decf8138f14b6ce8fa4c97f532404cfd **backwards** to https://github.com/oxidecomputer/hubris/commit/31dac53b98cbd1302b67ae98bcf35f213577801a, as that is the image present in dvt-dock. https://github.com/oxidecomputer/hubris/compare/31dac53b98cbd1302b67ae98bcf35f213577801a...b7529859decf8138f14b6ce8fa4c97f532404cfd

### CODE REVIEW

**Comment by rmustacc** [comment]
> For the sake of keeping wicket-driven updates simple, our TUF repo zips only contain one revision of each image. However, the dogfood rack and the DVT1 rack have different board revisions, which means we need different SP images.

The revisions are correct, but we've been calling this PVT. dogfood is built upon DVT hardware.

**Comment by iliana** [comment]
i keep getting those two confused in my head 😅

**Comment by iliana** [comment]
cross-referencing #3394

**Review by jgallagher — APPROVED** [review]
Double-checking the hubris contents of `repo-dogfood.zip`:

* all 3 SP archives match the gimlet-c / psc-b / sidecar-b archives from the pinned dvt-dock commit
* all 6 RoT archives match the `staging/dev` RoT archives from the pinned dvt-dock commit

Double-checking the hubris contents of `repo-pvt1.zip`:

* all 3 SP archives match the gimlet-d / psc-c / sidecar-c archives from the pinned dvt-dock commit
* all 6 RoT archives match the `prod/rel` archives from the pinned dvt-dock commit

**Pull request merged**
