### PR TITLE
Optimize OID lookup for user-defined types

### PR DESCRIPTION
**Pull request by smklein**
# Background

Looking up OIDs for ENUMs consumes a non-trival amount of time during initialization, since they are synchronously fetched one-by-one. Although this is amortized for long-lived connections, it incurs a cost on all tests using CRDB, and can be optimized. Additionally, these OID caches are per-connection, which incurs redundant work when we have a connection pool (and we do, with bb8). See #4733 for additional context.

Feedback from the Diesel maintainers:

> I think it would be reasonable to share this information at pool level...
>
> [OIDs are] currently queried by one type at the time as we argued that it won't matter for long running applications. There you do the overhead once per connection and then you just hit the cache. I don't think we did really consider short running applications (like tests) for that.

# This PR

1. Performs a one-time-lookup of user-defined ENUM OIDs on the first connection, and shares it between subsequent connections. This pre-populates the cache used by Diesel.
2. Modifies all `SqlType` derives to ensure that the `schema` is specified as `public` (this ensures a cache hit)
3. Adds a test to compare the "list of user-defined enums to look up" with the current DB schema, and ensures they're in-sync.

# Results

I focused on optimizing `integration_tests::basic::test_ping`, as this is very close to a "no-op" version of the `#[nexus_test]`. I wrote a script to repeatedly execute this test in a loop (excluding the first result, as a "warm-up" run to populate CRDB).

- Before: Average time over 10 runs: 10.42 seconds
- After: Average time over 10 runs: 9.47 seconds

That's a small difference, but hopefully it'll provide a dent over "all our tests", and avoid additional user-defined types from slowing down all tests.

Part of https://github.com/oxidecomputer/omicron/issues/4733

### CODE REVIEW

**Comment by smklein** [comment]
Checking the last few commits to main:

- build-and-test (ubuntu-22.04) Successful in 52m - Success!
- build-and-test (ubuntu-22.04) Successful in 49m - Success!
- build-and-test (ubuntu-22.04) Successful in 50m - Success!

And from nextest:

```
5206	2023-12-22T09:02:24.159Z	     Summary [1982.003s] 970 tests run: 970 passed (13 slow, 1 leaky), 3 skipped
5207	2023-12-22T09:02:24.164Z		Command being timed: "timeout 2h cargo nextest run --profile ci --locked --verbose"
5208	2023-12-22T09:02:24.168Z		User time (seconds): 9423.74
5209	2023-12-22T09:02:24.168Z		System time (seconds): 1377.74
5210	2023-12-22T09:02:24.168Z		Percent of CPU this job got: 543%
5211	2023-12-22T09:02:24.168Z		Elapsed (wall clock) time (h:mm:ss or m:ss): 33:06.69
```

This PR:
- build-and-test (ubuntu-22.04) Successful in 47m — Success!

```
5202	2023-12-29T00:46:42.395Z	     Summary [1853.552s] 972 tests run: 972 passed (9 slow, 1 leaky), 3 skipped
5203	2023-12-29T00:46:42.405Z		Command being timed: "timeout 2h cargo nextest run --profile ci --locked --verbose"
5204	2023-12-29T00:46:42.408Z		User time (seconds): 7717.26
5205	2023-12-29T00:46:42.408Z		System time (seconds): 1386.81
5206	2023-12-29T00:46:42.408Z		Percent of CPU this job got: 489%
5207	2023-12-29T00:46:42.408Z		Elapsed (wall clock) time (h:mm:ss or m:ss): 30:59.41
```

Seems like a small but "probably worth it" step - wall time drops by a couple minutes, and the total "User time" drops significantly.

**Review by andrewjstone — COMMENTED** [review]
@smklein This looks good. I like the new abstraction and the time savings are great. Thank you for doing this!

My one concern is about using this in production upgrade scenarios once we are running multiple versions of CRDB. I could guess at a couple of possible scenarios where we could mistakenly treat one enum value for another if the OIDs change. According to https://www.cockroachlabs.com/docs/v23.1/oid, OIDs are not guaranteed to be stable across versions. Could they also change with an alter table statement? For the first issue of version changes, diesel's original connection caching should continue to work. For the latter, even diesel as it works per connection would have this issue I believe.

I have no idea if these are actual problems that can exist, but figured I'd bring it up here as I was thinking about it.

**Comment by smklein** [comment]
> My one concern is about using this in production upgrade scenarios once we are running multiple versions of CRDB. I could guess at a couple of possible scenarios where we could mistakenly treat one enum value for another if the OIDs change. According to https://www.cockroachlabs.com/docs/v23.1/oid, OIDs are not guaranteed to be stable across versions. Could they also change with an alter table statement? For the first issue of version changes, diesel's original connection caching should continue to work. For the latter, even diesel as it works per connection would have this issue I believe.

These are good questions.

- On "OID stability across versions": I do agree that this is a potential problem. I tried to address this in fdf8dffa29b5a4e2edb0e3fafbfc0b0b7542b314 , by explicitly key-ing off the CRDB version, so "each time we access a new CRDB version, we treat it as a distinct cache". This gives me a *slightly* slower "average" time for the ping test: **Average time over 10 runs: 9.65 seconds.** However, this seems like a worthwhile trade-off, and should mitigate the potential instability across CRDB releases.

- On "ALTER TABLE statements": I *think*, reading https://github.com/cockroachdb/cockroach/pull/33697 , that these would be stable? As a reminder, the OID lookup isn't happening for arbitrary tables, but rather, just for user-created types, which is a slightly different scope -- I think this would actually be relevant for an `ALTER TYPE` statement instead.

I tried this manually on a single-node CRDB, and "adding a value, removing a value, and renaming the type" for an ENUM does not appear to change the OID. This isn't exhaustive, but at least it isn't trivially broken.

**Comment by andrewjstone** [comment]
> > My one concern is about using this in production upgrade scenarios once we are running multiple versions of CRDB. I could guess at a couple of possible scenarios where we could mistakenly treat one enum value for another if the OIDs change. According to https://www.cockroachlabs.com/docs/v23.1/oid, OIDs are not guaranteed to be stable across versions. Could they also change with an alter table statement? For the first issue of version changes, diesel's original connection caching should continue to work. For the latter, even diesel as it works per connection would have this issue I believe.
> 
> These are good questions.
> 
> * On "OID stability across versions": I do agree that this is a potential problem. I tried to address this in [fdf8dff](https://github.com/oxidecomputer/omicron/commit/fdf8dffa29b5a4e2edb0e3fafbfc0b0b7542b314) , by explicitly key-ing off the CRDB version, so "each time we access a new CRDB version, we treat it as a distinct cache". This gives me a _slightly_ slower "average" time for the ping test: **Average time over 10 runs: 9.65 seconds.** However, this seems like a worthwhile trade-off, and should mitigate the potential instability across CRDB releases.
> * On "ALTER TABLE statements": I _think_, reading [sql: make pg_catalog OIDs stable and refer to the descriptor IDs directly cockroachdb/cockroach#33697](https://github.com/cockroachdb/cockroach/pull/33697) , that these would be stable? As a reminder, the OID lookup isn't happening for arbitrary tables, but rather, just for user-created types, which is a slightly different scope -- I think this would actually be relevant for an `ALTER TYPE` statement instead.
> 
> I tried this manually on a single-node CRDB, and "adding a value, removing a value, and renaming the type" for an ENUM does not appear to change the OID. This isn't exhaustive, but at least it isn't trivially broken.

Wow, quick fix for the first issue! Thanks!

As for the second issue, you are right that `ALTER TYPE` is what we should be concerned about potentially. With that test, things seem to work as one would hope :)

**Review by andrewjstone — APPROVED** [review]
Looks great. Thank you @smklein!

**Pull request merged**
