### PR TITLE
[wicket] show PWR1 as empty, skip over it while tabbing over

### LINKED ISSUE #2559: [wicket] - Only populate pwr0
We will only have one powershelf, `pwr0`, running in production. We need to style the other powershelf so that it doesn't show up as present. We also should either remove `ComponentId::Psc1` or just always skip it in iteration. 

See https://github.com/oxidecomputer/omicron/pull/2440#issuecomment-1449135088

cc @rmustacc

### PR DESCRIPTION
**Pull request by sunshowers**
Our current shipping racks just have one power shelf, so show PWR1 as empty.

image

Closes #2559.

### CODE REVIEW

**Comment by rmustacc** [comment]
> Rename "PWR0" to just PWR.

Can we possibly not rename this? This should ideally match the external labeling that we have on the rack which still has the positional information. It's more accurate to show PWR1 as a blank. See https://rfd.shared.oxide.computer/rfd/0200#component_naming_conventions.

**Comment by rmustacc** [comment]
> Thanks @rmustacc -- I misunderstood what was required. Updated.

Much appreciated, thank you!

**Review by andrewjstone — APPROVED** [review]
Great stuff. Thanks!

**Comment by sunshowers** [comment]
Ugh, merged it to the dependent branch by accident. Will redo and land on main later.

**Pull request merged**
