### PR TITLE
[omicron-dev] make it feature-based, add xtask facade

### PR DESCRIPTION
**Pull request by sunshowers**
I've found myself wanting to run things like MGS via omicron-dev for a while,
but that process requiring all of Nexus to be built has always made it a bit
daunting. Use a set of features to ensure that the minimum set of dependencies
gets built. (And ensure that all of the options are built correctly via the
check-features xtask -- thanks Zeeshan!)

I'll also add a way to run wicketd via this path, and probably sled-agent-sim
as well.

### CODE REVIEW

**Comment by davepacheco** [comment]
I'm a little unclear on the goals here and so the complexity here doesn't seem worth it to me but I'm probably missing something about what we're trying to do so sorry about that!

> I've found myself wanting to run things like MGS via omicron-dev for a while,
> but that process requiring all of Nexus to be built has always made it a bit
> daunting. Use a set of features to ensure that the minimum set of dependencies
> gets built.

Is the problem here specifically that you want to use `omicron-dev` to launch MGS, but don't want to wait for it to build Nexus first?  I can see that.  The original vision for `omicron-dev` was a central home for various dev workflow tools, mainly for discoverability and ease of use.  But that approach assumed everybody working on Omicron would be building most of it anyway, which isn't really true today, so now people may end up building more than they need.  Plus, nowadays we have a whole dev-tools top-level directory and other binaries in there, including all of "xtask".   So maybe it makes more sense to split out omicron-dev's commands into separate tools?  i.e., why use features to build different subsets of this tool instead of having separate tools altogether?  That would seem a lot simpler and clearer (to me).

---

I don't follow what any of that has to do with the xtask wrapper for omicron-dev and other tools like sled-agent-sim.  I don't object to these per se.  But a big part of the motivation for the *manual* how-to-run-simulated approach is to have a documented way to run components with precise control over execution (e.g., so that you can run it under `mdb -c` or `dtrace -c` or `truss`; or so that you can precisely specify the environment, arguments, etc.).  So I'd rather those instructions refer to the lowest level commands, not wrappers.  And if that's true, it feels more confusing than it is helpful to have yet another way to run these things.  This isn't a big problem in this PR because your changes to how-to-run-simulated only affect things that were already using an `omicron-dev` wrapper (like `db-run` and `ch-run`) -- it's more a comment on the direction you mentioned in the description and why have an xtask for `omicron-dev` at all.  (Writing this also made me ask myself: if I care about being able to precisely run this stuff, why do those instructions use `omicron-dev db-run` instead of `cockroach` directly?  It's because Cockroach already documents how to run it by hand, and `omicron-dev db-run` spits out exactly how it's running it so that you can tweak it if you want, so the way things are now, you avoid the tedium of doing it _all_ yourself while still having enough information in the docs to be able to do that if you really need it.)

Or is the goal of the xtask wrapper clarity of organization?  If that's true I'm not sure it's better -- `xtask omicron-dev` seems kind of redundant (aren't xtasks usually dev tools?).

**Comment by sunshowers** [comment]
> Is the problem here specifically that you want to use omicron-dev to launch MGS, but don't want to wait for it to build Nexus first? I can see that. The original vision for omicron-dev was a central home for various dev workflow tools, mainly for discoverability and ease of use. But that approach assumed everybody working on Omicron would be building most of it anyway, which isn't really true today, so now people may end up building more than they need.

Yes, that's the overall goal. For example, while working on wicketd, if I modify `omicron-common`, I'd rather not wait for all of Nexus to build. That's why I put manual instructions for running MGS into the wicketd readme.

With this change, that is no longer necessary -- `cargo xtask omicron-dev mgs-run` builds MGS only.

> Plus, nowadays we have a whole dev-tools top-level directory and other binaries in there, including all of "xtask". So maybe it makes more sense to split out omicron-dev's commands into separate tools? i.e., why use features to build different subsets of this tool instead of having separate tools altogether? That would seem a lot simpler and clearer (to me).

I did consider this, but decided against it for a few reasons:

1. It would break existing workflows.
2. Parts of omicron-dev are likely to depend on other parts. For example, in a followup I'd like to add a `wicketd-run` command. That command would do everything that `mgs-run` does and more.
3. Each additional binary adds additional complexity with its own bookkeeping. For example, new dependencies might need to be added in several `Cargo.toml` files. (Features can be problematic for libraries because they'll end up being built many ways, but that isn't an issue for binaries/leaf nodes.)

These aren't insurmountable. We can communicate workflow breakage, and put shared code in a library or just copy it around. If we decide that the benefit of separate binaries outweighs the costs then that's okay. But I currently think that on balance a single binary with multiple feature flags makes the most sense.

> I don't follow what any of that has to do with the xtask wrapper for omicron-dev and other tools like sled-agent-sim. I don't object to these per se.

Without the `xtask` wrapper, users would have to manually select the feature they want. The wrapper takes care of that.

>  But a big part of the motivation for the manual how-to-run-simulated approach is to have a documented way to run components with precise control over execution (e.g., so that you can run it under mdb -c or dtrace -c or truss; or so that you can precisely specify the environment, arguments, etc.). So I'd rather those instructions refer to the lowest level commands, not wrappers. And if that's true, it feels more confusing than it is helpful to have yet another way to run these things.

That's an interesting use case. Could the xtask wrapper grow this functionality?

For example, imagine saying `cargo xtask omicron-dev -c "mdb -c" mgs-run`, where `-c`/`--wrap-command` is a command that's interspersed in between. We could even provide some commands as defaults, e.g. `cargo xtask omicron-dev --mdb mgs-run`.

> Writing this also made me ask myself: if I care about being able to precisely run this stuff, why do those instructions use omicron-dev db-run instead of cockroach directly? It's because Cockroach already documents how to run it by hand, and omicron-dev db-run spits out exactly how it's running it so that you can tweak it if you want, so the way things are now, you avoid the tedium of doing it all yourself while still having enough information in the docs to be able to do that if you really need it.

Right, exactly -- it's easier to run a well-known command than read through the docs and set up the ports appropriately etc. I really like the overall approach of omicron-dev, I'm just trying to make it better :)

> Or is the goal of the xtask wrapper clarity of organization? If that's true I'm not sure it's better -- xtask omicron-dev seems kind of redundant (aren't xtasks usually dev tools?).

As the PR currently stands, the goal of the xtask wrapper is selecting the right feature set and nothing else.

However, if we add `-c` and related functionality, then that would be an additional thing that the xtask wrapper can do.

**Comment by sunshowers** [comment]
> I tried giving omicron-dev mgs-run an honest shot, but iteration cycles were just too slow for my liking.

Actually now that I'm paging it in, an even worse issue than just build speed was the fact that updating common structs can break the Nexus build. (Similar to why API traits are useful.) I'd rather update Nexus once at the end than have to do it over and over in each iteration cycle.

**Comment by davepacheco** [comment]
> (Features can be problematic for libraries because they'll end up being built many ways and do a lot of transitive rebuilds, but that isn't an issue for binaries/leaf nodes.)

This might be the source of my confusion.  Using features for binaries does seem problematic.  Problems I'm imagining could happen: do you not need to rebuild omicron-dev if you switch between `cargo xtask omicron-dev` and `cargo run --bin=omicron-dev`?  If you run `./target/debug/omicron-dev`, couldn't you find that the binary only reports having some subset of the commands that you expect?  Might we start seeing problems with some unanticipated workflow where somebody runs an `omicron-dev` command and gets "command not found", but it's because they previously built it with the wrong features (or some consumer is not correctly specifying the features it needs)?  Doesn't it make it more complicated to work on `omicron-dev` because you have to be constantly testing various feature configurations?  This might just be fear on my part from lack of experience with features for binaries.  I just find it really surprising that two same-named binaries from the same tree could have different supported commands.  It's also possible I'm misunderstanding what would actually happen if you tried to do some of these things.

>>  But a big part of the motivation for the manual how-to-run-simulated approach is to have a documented way to run components with precise control over execution (e.g., so that you can run it under mdb -c or dtrace -c or truss; or so that you can precisely specify the environment, arguments, etc.). So I'd rather those instructions refer to the lowest level commands, not wrappers. And if that's true, it feels more confusing than it is helpful to have yet another way to run these things.
>
> That's an interesting use case. Could the xtask wrapper grow this functionality?
>
> For example, imagine saying cargo xtask omicron-dev -c "mdb -c" mgs-run, where -c/--wrap-command is a command that's interspersed in between. We could even provide some commands as defaults, e.g. cargo xtask omicron-dev --mdb mgs-run.

This is definitely possible, but in my experience this approach is more annoying and more limited.  It's more annoying because when commands accept CLI arguments that will be provided to subprocesses, it's often not clear if you're providing a raw argument list or a string that's going to be passed through `sh -c`, and so it's often hard to figure out how to quote things.  You may also need some syntax for inserting the command that the wrapper wants to run in case some other arguments are needed at the end of the command line.  In the examples I mentioned, dtrace is already doing this (in that case, because it's required to trace things early in the process lifetime), so you'd have something like `cargo xtask omicron-dev -c "dtrace -n 'your_probes' -c '...'"`.

I'm just noticing that `mdb` doesn't actually accept `-c`.  I think if you wanted to run it under mdb (e.g., to break at some early point in execution), I think you'd have to run `mdb /path/to/binary`, and then run `::run COMMAND_LINE_ARGUMENTS` interactively.  You might be able to do `mdb -e "::run COMMAND_LINE_ARGUMENTS" /path/to/binary` -- but this highlights the quoting issue and that you'd need a way to insert the arguments in some place other than the end of the command line.

I say this approach is more limited because there's lots of things you might need to control about the subprocess, not just the arguments.  You might want to change specific environment variables (including removing variables that are needed for the wrapper) or stdin/stdout (might work in this case if they're always inherited from the calling process) or the uid or privileges (maybe unlikely to come up for us?).  You might even want to run a specific binary, maybe one that you copied from another system or that you've modified in some way.

To be clear, I think these things are all fairly rare. But I think I've done all of them with parts of Omicron.  I'm all for having simpler ways for people to run things (which is what `run-all` is for the rest of the stack -- I get that it doesn't help people working on Wicket).  But this is the lowest-level, most manual documentation, specifically for when you want the extra control.  So I think it should explain how to run the low level pieces so that you can do whatever you want with them.

**Comment by sunshowers** [comment]
@davepacheco and I discussed this -- we're going to go with separate binary crates for each component, as in #6209.

**Pull request closed without merging**
