### PR TITLE
[sled-agent] Improve error message on ledger write failure

### PR DESCRIPTION
**Pull request by smklein**
Namely, identify the paths which we tried to access.

These would typically be "both mountpoints within M.2s", though it may be informative if we only try one (or none!) of them.

### CODE REVIEW

**Comment by davepacheco** [comment]
This looks good; can we also put the error message (or one of them) into the error that we return?

**Comment by smklein** [comment]
> This looks good; can we also put the error message (or one of them) into the error that we return?

Sure, it's a tuple of (PathBuf, Error) now.

**Review by davepacheco — APPROVED** [review]
Thanks for adding that!  What's it look like now?

**Comment by smklein** [comment]
> Thanks for adding that! What's it look like now?

This is the error I'm seeing in the test that removes the directories for both configs:

```
Failed to write the ledger to storage (tried to access: [("/tmp/.tmpJW4l0D/ledger.toml", Io { message: "Error accessing /tmp/.tmpJW4l0D/.ledger.toml.tmp", err: Os { code: 2, kind: NotFound, message: "No such file or directory" } }), ("/tmp/.tmp91lA2G/ledger.toml", Io { message: "Error accessing /tmp/.tmp91lA2G/.ledger.toml.tmp", err: Os { code: 2, kind: NotFound, message: "No such file or directory" } })])
```

**Pull request merged**
