### PR TITLE
Update propolis version

### PR DESCRIPTION
**Pull request by pfmooney**
Included changes:
Generate SMBIOS tables guest consumption
use for_internal_error for 500 error (#692)

### CODE REVIEW

**Review by leftwo — COMMENTED** [review]
Do you also need to update `Cargo.toml` as well?  So Omicron will compile with
the same git rev as the package will have?  I don't think there is any
actual required changes, but I know I always bump both files.

**Comment by pfmooney** [comment]
There have been no changes to the external API which would be reflected in what `propolis-client` exposes.  If I update those git revs, it drags in a bunch of other changes via `cargo update`.

**Review by leftwo — APPROVED** [review]
I do now believe that there is another Crucible bump coming, but that does not need to hold this back.

**Comment by pfmooney** [comment]
> I do now believe that there is another Crucible bump coming, but that does not need to hold this back.

If there's a crucible bump coming, I'll just defer to that, rather than tying up the CI queue for another build.

**Comment by leftwo** [comment]
The crucible bump was my mis-understanding, it was just new work to crucible main, not for release 8. So this can go go go!

**Pull request merged**
